<a href="https://colab.research.google.com/github/naffaziy24/genz-financial-behavior-analytics/blob/main/Dashboard_Analysis_Gelar_Rasa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data "Gen Z Financial Literacy Survey"

# Data Loading

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Import dataset

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/GELAR RASA/Dataset/GenZ_Financial_Literacy_Survey.csv', sep=';', quotechar='"', encoding='cp1252')

In [ ]:
df

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,...,Previously used decision strategies help me in better financial decision making,I am becoming financially secure,I am securing my financial future,I will achieve the financial goals that I have set for myself,I have saved (or will be able to save) enough money to last me to the end of my life,"Because of my money situation, I feel I will never have the things I want in life",I am behind with my finances,My finances control my life,"Whenever I feel in control of my finances, something happens that sets me back",I am unable to enjoy life because I obsess too much about money
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3,3,3,3.0,3,2.0,2,2,2,2
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3,3,3,3.0,4,3.0,2,3,3,2
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,...,3,3,3,3.0,3,1.0,2,2,2,2
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3,3,3,3.0,3,2.0,2,2,2,2
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3,3,3,3.0,3,3.0,2,3,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,...,3,2,2,3.0,2,2.0,3,2,2,4
1648,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,NaN,...,4,3,3,3.0,4,3.0,1,2,1,2
1649,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,...,2,2,3,3.0,3,1.0,2,3,2,1
1650,Female,DI Yogyakarta,NaN,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,NaN,< Rp2.000.000,...,2,1,3,4.0,2,3.0,1,3,4,2
1651,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,...,4,3,4,4.0,2,3.0,3,4,3,2

# Data Understanding

## Cek tipe data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1652 entries, 0 to 1651
Data columns (total 58 columns):
 #   Column                                                                                                                                                                            Non-Null Count  Dtype
---  ------                                                                                                                                                                            --------------  -----
 0   Gender                                                                                                                                                                            1538 non-null   object
 1   Province of Origin                                                                                                                                                                1652 non-null   object
 2   Random_Code                                                                                                                                                                       1234 non-null   object
 3   Residence Status                                                                                                                                                                  1652 non-null   object
 4   Last Education                                                                                                                                                                    1652 non-null   object
 5   Job                                                                                                                                                                               1652 non-null   object
 6   Marital Status                                                                                                                                                                    1652 non-null   object
 7   Year of Birth                                                                                                                                                                     1652 non-null   int64
 8   Est. Monthly Income                                                                                                                                                               1535 non-null   object
 9   Est. Monthly Expenditure                                                                                                                                                          1537 non-null   object
 10  I am able to identify risks and discrepancies and view numbers in a complex way                                                                                                   1652 non-null   int64
 11  I am able to recognize a good financial investment                                                                                                                                1652 non-null   int64
 12  I am able to understand what is behind the numbers                                                                                                                                1652 non-null   int64
 13  I am able to and divide it accordingly across an allotted period to the right concerned areas                                                                                     1652 non-null   int64
 14  I am able to project the amount of cash that will be available to me in the future                                                                                                1652 non-null   int64
 15  I am able to plan ahead to avoid impulse spending                                                                                                                                 1652 non-null   int64
 16  I am able to understand numbers and financial metrics                                                                                                                             1652 non-null   object
 17  I am able to understand what drives cash flow and profits                                                                                                                         1651 non-null   float64
 18  I am able to understand the company's financial statements and some core performance measures                                                                                     1651 non-null   float64
 19  Awareness about the potential of financial risk in using digital financial provider or fintech, such as the legality of the fintech provider, interest rate and transaction fee   1652 non-null   int64
 20  Having experience in using the product and service of fintech for digital payment                                                                                                 1652 non-null   int64
 21  Experience in using the product and service of fintech for financing (loan) and investment                                                                                        1652 non-null   int64
 22  Experience in using the product and service of fintech for asset management                                                                                                       1651 non-null   float64
 23  Having a good understanding of digital payment products such as E-Debit, E-Credit, E-Money, Mobile/Internet banking, E -wallet                                                    1651 non-null   object
 24  Having a good understanding of product digital asset management                                                                                                                   1652 non-null   int64
 25  Having a good understanding of digital alternatives                                                                                                                               1652 non-null   object
 26  Having a good understanding of digital insurance                                                                                                                                  1652 non-null   int64
 27  Having a good understanding of customer rights and protection as well as the procedure to complain about the service from digital  financial providers                            1647 non-null   float64
 28  I take part in domestic expense planning                                                                                                                                          1652 non-null   int64
 29  I usually have a critical view of the way my friends deal with money                                                                                                              1652 non-null   object
 30  I like to participate in family decision making when we buy something expensive for home                                                                                          1652 non-null   int64
 31  I advise others on money matters                                                                                                                                                  1650 non-null   float64
 32  I always try to save some money to do things I really like                                                                                                                        1652 non-null   int64
 33  I always like to negotiate prices when I buy                                                                                                                                      1652 non-null   int64
 34  I suggest at home that we keep money aside for emergencies                                                                                                                        1651 non-null   object
 35  I keep an eye on promotions and discounts                                                                                                                                         1652 non-null   int64
 36  I like to think thoroughly before deciding to buy something                                                                                                                       1652 non-null   int64
 37  I like to research prices whenever I buy something                                                                                                                                1651 non-null   object
 38  I pay attention to news about the economy as it may affect my family                                                                                                              1652 non-null   object
 39  I often do things without giving them much thought                                                                                                                                1652 non-null   int64
 40  I am impulsive                                                                                                                                                                    1652 non-null   int64
 41  I say things before I have thought them through                                                                                                                                   1652 non-null   int64
 42  I am able to quickly change my financial decisions as per the changes in circumstance                                                                                             1652 non-null   int64
 43  Appraise of personal risk helps me in better financial decision making                                                                                                            1652 non-null   int64
 44  I make sound financial decision by comparing results over the time                                                                                                                1652 non-null   int64
 45  I make sound financial decisions by comparing results over expenses involved                                                                                                      1652 non-null   int64
 46  I am able to search for economic options during financial decision making                                                                                                         1652 non-null   int64
 47  I am able to foresee the long term and short-term consequences of the financial decisions I undertake                                                                             1652 non-null   int64
 48  Previously used decision strategies help me in better financial decision making                                                                                                   1652 non-null   int64
 49  I am becoming financially secure                                                                                                                                                  1652 non-null   int64
 50  I am securing my financial future                                                                                                                                                 1652 non-null   int64
 51  I  will achieve the financial goals that I have set for myself                                                                                                                    1644 non-null   float64
 52  I have saved (or will be able to save) enough money to last me to the end of my life                                                                                              1652 non-null   int64
 53  Because of my money situation, I feel I will never have the things I want in life                                                                                                 1651 non-null   float64
 54  I am behind with my finances                                                                                                                                                      1652 non-null   int64
 55  My finances control my life                                                                                                                                                       1652 non-null   int64
 56  Whenever I feel in control of my finances, something happens that sets me back                                                                                                    1652 non-null   int64
 57  I am unable to enjoy life because I obsess too much about money                                                                                                                   1652 non-null   int64
dtypes: float64(7), int64(35), object(16)
memory usage: 748.7+ KB

## Cek duplikat

In [ ]:
df.duplicated().sum()

np.int64(7)

In [ ]:
duplicate_rows = df[df.duplicated(keep=False)]
display(duplicate_rows)

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,...,Previously used decision strategies help me in better financial decision making,I am becoming financially secure,I am securing my financial future,I will achieve the financial goals that I have set for myself,I have saved (or will be able to save) enough money to last me to the end of my life,"Because of my money situation, I feel I will never have the things I want in life",I am behind with my finances,My finances control my life,"Whenever I feel in control of my finances, something happens that sets me back",I am unable to enjoy life because I obsess too much about money
636,Male,DKI Jakarta,A12X,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2002,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,...,3,3,3,4.0,3,3.0,3,4,3,3
639,Male,DKI Jakarta,A12X,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2002,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,...,3,3,3,4.0,3,3.0,3,4,3,3
648,Wanita,Central Java,A12X,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Rp4.000.001 – Rp6.000.000,< Rp2.000.000,...,3,3,4,3.0,3,3.0,2,2,2,3
651,Wanita,Central Java,A12X,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Rp4.000.001 – Rp6.000.000,< Rp2.000.000,...,3,3,4,3.0,3,3.0,2,2,2,3
655,Wanita,DI Yogyakarta,B99Z,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,...,4,3,4,3.0,4,3.0,3,2,2,2
658,Wanita,DI Yogyakarta,B99Z,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,...,4,3,4,3.0,4,3.0,3,2,2,2
663,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,NaN,...,4,3,3,3.0,4,3.0,1,2,1,2
687,Male,DKI Jakarta,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,NaN,...,3,3,3,2.0,2,2.0,2,2,2,2
733,Female,North Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,...,3,4,3,3.0,3,3.0,2,2,2,3
737,Female,North Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,...,3,4,3,3.0,3,3.0,2,2,2,3
1267,Female,Central Java,B99Z,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,< Rp2.000.000,Rp2.000.001 – Rp4.000.000,...,1,3,4,2.0,3,4.0,4,3,4,4
1633,Female,Central Java,B99Z,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,< Rp2.000.000,Rp2.000.001 – Rp4.000.000,...,1,3,4,2.0,3,4.0,4,3,4,4
1635,Male,DKI Jakarta,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,NaN,...,3,3,3,2.0,2,2.0,2,2,2,2
1648,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,NaN,...,4,3,3,3.0,4,3.0,1,2,1,2

### Hapus duplikat

In [ ]:
# Sebelum
print("Jumlah baris sebelum drop_duplicates:", len(df))
df = df.drop_duplicates()
print("Jumlah baris setelah drop_duplicates:", len(df))

Jumlah baris sebelum drop_duplicates: 1652
Jumlah baris setelah drop_duplicates: 1645

In [ ]:
df.duplicated().sum()

np.int64(0)

## Missing Value

In [ ]:
df.isnull().sum()

Gender                                                                                                                                                                              114
Province of Origin                                                                                                                                                                    0
Random_Code                                                                                                                                                                         418
Residence Status                                                                                                                                                                      0
Last Education                                                                                                                                                                        0
Job                                                                                                                                                                                   0
Marital Status                                                                                                                                                                        0
Year of Birth                                                                                                                                                                         0
Est. Monthly Income                                                                                                                                                                 117
Est. Monthly Expenditure                                                                                                                                                            115
I am able to identify risks and discrepancies and view numbers in a complex way                                                                                                       0
I am able to recognize a good financial investment                                                                                                                                    0
I am able to understand what is behind the numbers                                                                                                                                    0
I am able to and divide it accordingly across an allotted period to the right concerned areas                                                                                         0
I am able to project the amount of cash that will be available to me in the future                                                                                                    0
I am able to plan ahead to avoid impulse spending                                                                                                                                     0
I am able to understand numbers and financial metrics                                                                                                                                 0
I am able to understand what drives cash flow and profits                                                                                                                             1
I am able to understand the company's financial statements and some core performance measures                                                                                         1
Awareness about the potential of financial risk in using digital financial provider or fintech, such as the legality of the fintech provider, interest rate and transaction fee       0
Having experience in using the product and service of fintech for digital payment                                                                                                     0
Experience in using the product and service of fintech for financing (loan) and investment                                                                                            0
Experience in using the product and service of fintech for asset management                                                                                                           1
Having a good understanding of digital payment products such as E-Debit, E-Credit, E-Money, Mobile/Internet banking, E -wallet                                                        1
Having a good understanding of product digital asset management                                                                                                                       0
Having a good understanding of digital alternatives                                                                                                                                   0
Having a good understanding of digital insurance                                                                                                                                      0
Having a good understanding of customer rights and protection as well as the procedure to complain about the service from digital  financial providers                                5
I take part in domestic expense planning                                                                                                                                              0
I usually have a critical view of the way my friends deal with money                                                                                                                  0
I like to participate in family decision making when we buy something expensive for home                                                                                              0
I advise others on money matters                                                                                                                                                      2
I always try to save some money to do things I really like                                                                                                                            0
I always like to negotiate prices when I buy                                                                                                                                          0
I suggest at home that we keep money aside for emergencies                                                                                                                            1
I keep an eye on promotions and discounts                                                                                                                                             0
I like to think thoroughly before deciding to buy something                                                                                                                           0
I like to research prices whenever I buy something                                                                                                                                    1
I pay attention to news about the economy as it may affect my family                                                                                                                  0
I often do things without giving them much thought                                                                                                                                    0
I am impulsive                                                                                                                                                                        0
I say things before I have thought them through                                                                                                                                       0
I am able to quickly change my financial decisions as per the changes in circumstance                                                                                                 0
Appraise of personal risk helps me in better financial decision making                                                                                                                0
I make sound financial decision by comparing results over the time                                                                                                                    0
I make sound financial decisions by comparing results over expenses involved                                                                                                          0
I am able to search for economic options during financial decision making                                                                                                             0
I am able to foresee the long term and short-term consequences of the financial decisions I undertake                                                                                 0
Previously used decision strategies help me in better financial decision making                                                                                                       0
I am becoming financially secure                                                                                                                                                      0
I am securing my financial future                                                                                                                                                     0
I  will achieve the financial goals that I have set for myself                                                                                                                        8
I have saved (or will be able to save) enough money to last me to the end of my life                                                                                                  0
Because of my money situation, I feel I will never have the things I want in life                                                                                                     1
I am behind with my finances                                                                                                                                                          0
My finances control my life                                                                                                                                                           0
Whenever I feel in control of my finances, something happens that sets me back                                                                                                        0
I am unable to enjoy life because I obsess too much about money                                                                                                                       0
dtype: int64

In [ ]:
rows_with_missing_values = df[df.isnull().any(axis=1)]
display(rows_with_missing_values)

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,...,Previously used decision strategies help me in better financial decision making,I am becoming financially secure,I am securing my financial future,I will achieve the financial goals that I have set for myself,I have saved (or will be able to save) enough money to last me to the end of my life,"Because of my money situation, I feel I will never have the things I want in life",I am behind with my finances,My finances control my life,"Whenever I feel in control of my finances, something happens that sets me back",I am unable to enjoy life because I obsess too much about money
11,Female,West Sumatera,NaN,Rental House,Diploma I/II/III,Student,Not Married,1999,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,...,4,3,3,4.0,3,2.0,2,2,2,2
13,Male,West Sumatera,NaN,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3,3,3,3.0,3,2.0,3,2,2,2
14,F,West Sumatera,NaN,Parent’s House,Diploma I/II/III,Student,Not Married,1999,< Rp2.000.000,NaN,...,3,3,3,4.0,4,2.0,3,2,2,1
16,F,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,NaN,< Rp2.000.000,...,4,3,3,3.0,1,3.0,3,1,2,1
18,Male,West Sumatera,A12X,Rental House,Diploma I/II/III,Student,Not Married,2000,NaN,Rp2.000.001 – Rp4.000.000,...,4,1,3,3.0,2,3.0,3,3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1641,Female,West Sumatera,NaN,Parent’s House,Diploma I/II/III,Private Employee,Not Married,2000,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,...,3,3,3,3.0,3,2.0,2,2,2,2
1642,Pria,West Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2001,< Rp.2.000.000,< Rp2.000.000,...,3,3,3,3.0,3,3.0,3,3,3,3
1646,Male,West Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2000,NaN,< Rp2.000.000,...,3,3,2,3.0,2,1.0,2,1,1,1
1648,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,NaN,...,4,3,3,3.0,4,3.0,1,2,1,2
1650,Female,DI Yogyakarta,NaN,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,NaN,< Rp2.000.000,...,2,1,3,4.0,2,3.0,1,3,4,2

### Penangan Missing value Gender

In [ ]:
df['Gender'] = df['Gender'].fillna('Unknown')

/tmp/ipython-input-2522052258.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].fillna('Unknown')

### Penanganan Missing Value Monthly Income

In [ ]:
df['Est. Monthly Income'] = df['Est. Monthly Income'].fillna('Unknown')

/tmp/ipython-input-2584068973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Est. Monthly Income'] = df['Est. Monthly Income'].fillna('Unknown')

### Penanganan Missing Value Monthly Expenditure

In [ ]:
df['Est. Monthly Expenditure'] = df['Est. Monthly Expenditure'].fillna('Unknown')

/tmp/ipython-input-4129757454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Est. Monthly Expenditure'] = df['Est. Monthly Expenditure'].fillna('Unknown')

### Penanganan Missing Value Random Code

In [ ]:
df['Random_Code'] = df['Random_Code'].fillna('Unknown')

/tmp/ipython-input-2673400329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Random_Code'] = df['Random_Code'].fillna('Unknown')

In [ ]:
# --- Langkah 1: Tentukan kolom pertanyaan ---
question_cols = [
    'I am able to identify risks and discrepancies and view numbers in a complex way',
    'I am able to recognize a good financial investment',
    'I am able to understand what is behind the numbers',
    'I am able to and divide it accordingly across an allotted period to the right concerned areas',
    'I am able to project the amount of cash that will be available to me in the future',
    'I am able to plan ahead to avoid impulse spending',
    'I am able to understand numbers and financial metrics',
    'I am able to understand what drives cash flow and profits',
    "I am able to understand the company's financial statements and some core performance measures",
    'Awareness about the potential of financial risk in using digital financial provider or fintech, such as the legality of the fintech provider, interest rate and transaction fee',
    'Having experience in using the product and service of fintech for digital payment',
    'Experience in using the product and service of fintech for financing (loan) and investment',
    'Experience in using the product and service of fintech for asset management',
    'Having a good understanding of digital payment products such as E-Debit, E-Credit, E-Money, Mobile/Internet banking, E -wallet',
    'Having a good understanding of product digital asset management',
    'Having a good understanding of digital alternatives',
    'Having a good understanding of digital insurance',
    'Having a good understanding of customer rights and protection as well as the procedure to complain about the service from digital financial providers',
    'I take part in domestic expense planning',
    'I usually have a critical view of the way my friends deal with money',
    'I like to participate in family decision making when we buy something expensive for home',
    'I advise others on money matters',
    'I always try to save some money to do things I really like',
    'I always like to negotiate prices when I buy',
    'I suggest at home that we keep money aside for emergencies',
    'I keep an eye on promotions and discounts',
    'I like to think thoroughly before deciding to buy something',
    'I like to research prices whenever I buy something',
    'I pay attention to news about the economy as it may affect my family',
    'I often do things without giving them much thought',
    'I am impulsive',
    'I say things before I have thought them through',
    'I am able to quickly change my financial decisions as per the changes in circumstance',
    'Appraise of personal risk helps me in better financial decision making',
    'I make sound financial decision by comparing results over the time',
    'I make sound financial decisions by comparing results over expenses involved',
    'I am able to search for economic options during financial decision making',
    'I am able to foresee the long term and short-term consequences of the financial decisions I undertake',
    'Previously used decision strategies help me in better financial decision making',
    'I am becoming financially secure',
    'I am securing my financial future',
    'I will achieve the financial goals that I have set for myself',
    'I have saved (or will be able to save) enough money to last me to the end of my life',
    'Because of my money situation, I feel I will never have the things I want in life',
    'I am behind with my finances',
    'My finances control my life',
    'Whenever I feel in control of my finances, something happens that sets me back',
    'I am unable to enjoy life because I obsess too much about money'
]

# --- Langkah 2: Filter kolom pertanyaan yang ada di DataFrame ---
existing_question_cols = [col for col in question_cols if col in df.columns]

# --- Langkah 3: Isi missing value dengan 0 di kolom pertanyaan yang ada ---
df[existing_question_cols] = df[existing_question_cols].fillna(0)


# --- Langkah 4: Cek hasil ---
missing_after = df[existing_question_cols].isna().sum().sum()
print(f"✅ Jumlah missing value setelah imputasi: {missing_after}")

✅ Jumlah missing value setelah imputasi: 0

/tmp/ipython-input-3699289927.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[existing_question_cols] = df[existing_question_cols].fillna(0)

In [ ]:
df.isnull().sum()

Gender                                                                                                                                                                             0
Province of Origin                                                                                                                                                                 0
Random_Code                                                                                                                                                                        0
Residence Status                                                                                                                                                                   0
Last Education                                                                                                                                                                     0
Job                                                                                                                                                                                0
Marital Status                                                                                                                                                                     0
Year of Birth                                                                                                                                                                      0
Est. Monthly Income                                                                                                                                                                0
Est. Monthly Expenditure                                                                                                                                                           0
I am able to identify risks and discrepancies and view numbers in a complex way                                                                                                    0
I am able to recognize a good financial investment                                                                                                                                 0
I am able to understand what is behind the numbers                                                                                                                                 0
I am able to and divide it accordingly across an allotted period to the right concerned areas                                                                                      0
I am able to project the amount of cash that will be available to me in the future                                                                                                 0
I am able to plan ahead to avoid impulse spending                                                                                                                                  0
I am able to understand numbers and financial metrics                                                                                                                              0
I am able to understand what drives cash flow and profits                                                                                                                          0
I am able to understand the company's financial statements and some core performance measures                                                                                      0
Awareness about the potential of financial risk in using digital financial provider or fintech, such as the legality of the fintech provider, interest rate and transaction fee    0
Having experience in using the product and service of fintech for digital payment                                                                                                  0
Experience in using the product and service of fintech for financing (loan) and investment                                                                                         0
Experience in using the product and service of fintech for asset management                                                                                                        0
Having a good understanding of digital payment products such as E-Debit, E-Credit, E-Money, Mobile/Internet banking, E -wallet                                                     0
Having a good understanding of product digital asset management                                                                                                                    0
Having a good understanding of digital alternatives                                                                                                                                0
Having a good understanding of digital insurance                                                                                                                                   0
Having a good understanding of customer rights and protection as well as the procedure to complain about the service from digital financial providers                              0
I take part in domestic expense planning                                                                                                                                           0
I usually have a critical view of the way my friends deal with money                                                                                                               0
I like to participate in family decision making when we buy something expensive for home                                                                                           0
I advise others on money matters                                                                                                                                                   0
I always try to save some money to do things I really like                                                                                                                         0
I always like to negotiate prices when I buy                                                                                                                                       0
I suggest at home that we keep money aside for emergencies                                                                                                                         0
I keep an eye on promotions and discounts                                                                                                                                          0
I like to think thoroughly before deciding to buy something                                                                                                                        0
I like to research prices whenever I buy something                                                                                                                                 0
I pay attention to news about the economy as it may affect my family                                                                                                               0
I often do things without giving them much thought                                                                                                                                 0
I am impulsive                                                                                                                                                                     0
I say things before I have thought them through                                                                                                                                    0
I am able to quickly change my financial decisions as per the changes in circumstance                                                                                              0
Appraise of personal risk helps me in better financial decision making                                                                                                             0
I make sound financial decision by comparing results over the time                                                                                                                 0
I make sound financial decisions by comparing results over expenses involved                                                                                                       0
I am able to search for economic options during financial decision making                                                                                                          0
I am able to foresee the long term and short-term consequences of the financial decisions I undertake                                                                              0
Previously used decision strategies help me in better financial decision making                                                                                                    0
I am becoming financially secure                                                                                                                                                   0
I am securing my financial future                                                                                                                                                  0
I will achieve the financial goals that I have set for myself                                                                                                                      0
I have saved (or will be able to save) enough money to last me to the end of my life                                                                                               0
Because of my money situation, I feel I will never have the things I want in life                                                                                                  0
I am behind with my finances                                                                                                                                                       0
My finances control my life                                                                                                                                                        0
Whenever I feel in control of my finances, something happens that sets me back                                                                                                     0
I am unable to enjoy life because I obsess too much about money                                                                                                                    0
dtype: int64

# Nilai Unique Random Code

In [ ]:
print("Nilai unik dari kolom 'Random_Code':")
print(df['Random_Code'].unique())

Nilai unik dari kolom 'Random_Code':
['B99Z' 'A96P' 'C77Q' 'A12X' 'Unknown' 'BA4C']

# Nilai Unique Est. Monthly Income

In [ ]:
print("Nilai unik dari kolom 'Est. Monthly Income':")
print(df['Est. Monthly Income'].unique())

Nilai unik dari kolom 'Est. Monthly Income':
['< Rp2.000.000' 'Rp2.000.001 – Rp4.000.000' 'Rp4.000.001 – Rp6.000.000'
 'Unknown' 'Rp.2.000.001 â€“ Rp.4.000.000' 'Rp6.000.001 – Rp10.000.000'
 'Rp10.000.001 – Rp15.000.000' '< Rp.2.000.000' '> Rp15.000.000'
 'Rp.6.000.001 â€“ Rp.10.000.000' 'Rp.4.000.001 â€“ Rp.6.000.000']

In [ ]:
import re

# Bersihkan karakter aneh dan spasi
df['Est. Monthly Income'] = (
    df['Est. Monthly Income']
    .astype(str)
    .str.replace(r'[^\w\s\.\<\>\-Rp]', '', regex=True)  # hapus karakter aneh (seperti â€“)
    .str.replace(r'\s+', ' ', regex=True)               # rapikan spasi
    .str.strip()                                        # hapus spasi di awal/akhir
)

#  Buat peta nilai kategori standar
income_mapping = {
    '< Rp2.000.000': '< Rp2.000.000',
    'Rp2.000.001 - Rp4.000.000': 'Rp2.000.001 - Rp4.000.000',
    'Rp4.000.001 - Rp6.000.000': 'Rp4.000.001 - Rp6.000.000',
    'Rp6.000.001 - Rp10.000.000': 'Rp6.000.001 - Rp10.000.000',
    'Rp10.000.001 - Rp15.000.000': 'Rp10.000.001 - Rp15.000.000',
    '> Rp15.000.000': '> Rp15.000.000',
    'Unknown': 'Unknown'
}

#  Bersihkan format variasi yang mirip
def normalize_income(val):
    if pd.isna(val) or val.strip() == '':
        return 'Unknown'
    text = val.replace('â€“', '-').replace('–', '-').replace('—', '-').replace('–', '-')
    text = text.replace('Rp.', 'Rp').replace('Rp ', 'Rp').replace('  ', ' ')
    text = text.strip()

    # Cari padanan yang cocok di mapping
    for k in income_mapping:
        if all(part in text for part in re.findall(r'Rp\d', k)):  # cocokkan pola angka
            return income_mapping[k]
    # fallback
    for key in income_mapping.keys():
        if key in text:
            return income_mapping[key]
    return 'Unknown'

df['Est. Monthly Income'] = df['Est. Monthly Income'].apply(normalize_income)

/tmp/ipython-input-1393536575.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Est. Monthly Income'] = (
/tmp/ipython-input-1393536575.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Est. Monthly Income'] = df['Est. Monthly Income'].apply(normalize_income)

In [ ]:
print("Nilai unik dari kolom 'Est. Monthly Income':")
print(df['Est. Monthly Income'].unique())

Nilai unik dari kolom 'Est. Monthly Income':
['< Rp2.000.000' 'Rp4.000.001 - Rp6.000.000' 'Unknown'
 'Rp6.000.001 - Rp10.000.000' 'Rp10.000.001 - Rp15.000.000']

In [ ]:
print("Nilai unik dari kolom 'Est. Monthly Expenditure':")
print(df['Est. Monthly Expenditure'].unique())

Nilai unik dari kolom 'Est. Monthly Expenditure':
['< Rp2.000.000' 'Rp4.000.001 – Rp6.000.000' 'Rp2.000.001 – Rp4.000.000'
 'Unknown' 'Rp6.000.001 – Rp10.000.000' 'Rp10.000.001 – Rp15.000.000']

# Data Merged "Gen Z financial literacy"

In [ ]:
# 3️⃣ Definisikan kelompok kolom berdasarkan kategori
financial_knowledge = [
    "I am able to identify risks and discrepancies and view numbers in a complex way",
    "I am able to recognize a good financial investment",
    "I am able to understand what is behind the numbers",
    "I am able to and divide it accordingly across an allotted period to the right concerned areas",
    "I am able to project the amount of cash that will be available to me in the future",
    "I am able to plan ahead to avoid impulse spending",
    "I am able to understand numbers and financial metrics",
    "I am able to understand what drives cash flow and profits",
    "I am able to understand the company's financial statements and some core performance measures"
]

fintech_literacy = [
    "Awareness about the potential of financial risk in using digital financial provider or fintech, such as the legality of the fintech provider, interest rate and transaction fee",
    "Having experience in using the product and service of fintech for digital payment",
    "Experience in using the product and service of fintech for financing (loan) and investment",
    "Experience in using the product and service of fintech for asset management",
    "Having a good understanding of digital payment products such as E-Debit, E-Credit, E-Money, Mobile/Internet banking, E -wallet",
    "Having a good understanding of product digital asset management",
    "Having a good understanding of digital alternatives",
    "Having a good understanding of digital insurance",
    "Having a good understanding of customer rights and protection as well as the procedure to complain about the service from digital financial providers" # Corrected column name
]

financial_behavior = [
    "I take part in domestic expense planning",
    "I usually have a critical view of the way my friends deal with money",
    "I like to participate in family decision making when we buy something expensive for home",
    "I advise others on money matters",
    "I always try to save some money to do things I really like",
    "I always like to negotiate prices when I buy",
    "I suggest at home that we keep money aside for emergencies",
    "I keep an eye on promotions and discounts",
    "I like to think thoroughly before deciding to buy something",
    "I like to research prices whenever I buy something",
    "I pay attention to news about the economy as it may affect my family"
]

financial_decision = [
    "I often do things without giving them much thought",
    "I am impulsive",
    "I say things before I have thought them through",
    "I am able to quickly change my financial decisions as per the changes in circumstance",
    "Appraise of personal risk helps me in better financial decision making",
    "I make sound financial decision by comparing results over the time",
    "I make sound financial decisions by comparing results over expenses involved",
    "I am able to search for economic options during financial decision making",
    "I am able to foresee the long term and short-term consequences of the financial decisions I undertake",
    "Previously used decision strategies help me in better financial decision making"
]

financial_wellbeing = [
    "I am becoming financially secure",
    "I am securing my financial future",
    "I have saved (or will be able to save) enough money to last me to the end of my life",
    "Because of my money situation, I feel I will never have the things I want in life",
    "I am behind with my finances",
    "My finances control my life",
    "Whenever I feel in control of my finances, something happens that sets me back",
    "I am unable to enjoy life because I obsess too much about money"
]

# 4️⃣ Konversi semua kolom terkait ke numeric (untuk amankan tipe data)
for cols in [financial_knowledge, fintech_literacy, financial_behavior, financial_decision, financial_wellbeing]:
    for c in cols:
        df[c] = pd.to_numeric(df[c], errors='coerce')

# 5️⃣ Hitung rata-rata skor tiap kategori untuk setiap responden
df['Financial_Knowledge_Score'] = df[financial_knowledge].mean(axis=1)
df['Fintech_Literacy_Score'] = df[fintech_literacy].mean(axis=1)
df['Financial_Behavior_Score'] = df[financial_behavior].mean(axis=1)
df['Financial_Decision_Score'] = df[financial_decision].mean(axis=1)
df['Financial_Wellbeing_Score'] = df[financial_wellbeing].mean(axis=1)

# 6️⃣ Simpan hanya skor akhir + kolom identitas (jika ada, misal ID atau Demografi)
columns_for_dashboard = [
    'Financial_Knowledge_Score',
    'Fintech_Literacy_Score',
    'Financial_Behavior_Score',
    'Financial_Decision_Score',
    'Financial_Wellbeing_Score'
]

dashboard_df = df[columns_for_dashboard]

# 7️⃣ (Opsional) Simpan hasilnya ke file baru
dashboard_df.to_csv("/content/drive/MyDrive/GELAR RASA/Dataset/GenZ_Financial_Score.csv", index=False)

print("✅ Selesai! File skor kategori siap dipakai untuk dashboard.")
display(dashboard_df.head())

/tmp/ipython-input-2775927036.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[c] = pd.to_numeric(df[c], errors='coerce')
/tmp/ipython-input-2775927036.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Financial_Knowledge_Score'] = df[financial_knowledge].mean(axis=1)
/tmp/ipython-input-2775927036.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Fintech_Literacy_Score'] = df[fintech_literacy].mean(axis=1)
/tmp/ipython-input-2775927036.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Financial_Behavior_Score'] = df[financial_behavior].mean(axis=1)
/tmp/ipython-input-2775927036.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Financial_Decision_Score'] = df[financial_decision].mean(axis=1)
/tmp/ipython-input-2775927036.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Financial_Wellbeing_Score'] = df[financial_wellbeing].mean(axis=1)

✅ Selesai! File skor kategori siap dipakai untuk dashboard.

,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,3.444444,2.444444,3.090909,2.7,2.375
1,2.888889,3.222222,3.000000,2.6,2.875
2,3.111111,2.555556,2.909091,2.7,2.250
3,2.777778,2.444444,2.727273,2.5,2.375
4,3.222222,3.777778,3.909091,2.8,2.625

In [ ]:
# Ubah tampilan angka desimal di pandas
pd.options.display.float_format = '{:.1f}'.format

# Lihat hasil
dashboard_df.head()

,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,3.4,2.4,3.1,2.7,2.4
1,2.9,3.2,3.0,2.6,2.9
2,3.1,2.6,2.9,2.7,2.2
3,2.8,2.4,2.7,2.5,2.4
4,3.2,3.8,3.9,2.8,2.6

In [ ]:
# 2️⃣ Hapus kolom pertanyaan panjang dari df
# (anggap kolom skor baru akan menggantikan semuanya)
# Misalnya semua kolom pertanyaan berada setelah kolom ke-5:
pertanyaan_columns = [
    "I am able to identify risks and discrepancies and view numbers in a complex way",
    "I am able to recognize a good financial investment",
    "I am able to understand what is behind the numbers",
    "I am able to and divide it accordingly across an allotted period to the right concerned areas",
    "I am able to project the amount of cash that will be available to me in the future",
    "I am able to plan ahead to avoid impulse spending",
    "I am able to understand numbers and financial metrics",
    "I am able to understand what drives cash flow and profits",
    "I am able to understand the company's financial statements and some core performance measures",
    "Awareness about the potential of financial risk in using digital financial provider or fintech, such as the legality of the fintech provider, interest rate and transaction fee",
    "Having experience in using the product and service of fintech for digital payment",
    "Experience in using the product and service of fintech for financing (loan) and investment",
    "Experience in using the product and service of fintech for asset management",
    "Having a good understanding of digital payment products such as E-Debit, E-Credit, E-Money, Mobile/Internet banking, E -wallet",
    "Having a good understanding of product digital asset management",
    "Having a good understanding of digital alternatives",
    "Having a good understanding of digital insurance",
    "Having a good understanding of customer rights and protection as well as the procedure to complain about the service from digital financial providers",
    "I take part in domestic expense planning",
    "I usually have a critical view of the way my friends deal with money",
    "I like to participate in family decision making when we buy something expensive for home",
    "I advise others on money matters",
    "I always try to save some money to do things I really like",
    "I always like to negotiate prices when I buy",
    "I suggest at home that we keep money aside for emergencies",
    "I keep an eye on promotions and discounts",
    "I like to think thoroughly before deciding to buy something",
    "I like to research prices whenever I buy something",
    "I pay attention to news about the economy as it may affect my family",
    "I often do things without giving them much thought",
    "I am impulsive",
    "I say things before I have thought them through",
    "I am able to quickly change my financial decisions as per the changes in circumstance",
    "Appraise of personal risk helps me in better financial decision making",
    "I make sound financial decision by comparing results over the time",
    "I make sound financial decisions by comparing results over expenses involved",
    "I am able to search for economic options during financial decision making",
    "I am able to foresee the long term and short-term consequences of the financial decisions I undertake",
    "Previously used decision strategies help me in better financial decision making",
    "I am becoming financially secure",
    "I am securing my financial future",
    "I have saved (or will be able to save) enough money to last me to the end of my life",
    "Because of my money situation, I feel I will never have the things I want in life",
    "I am behind with my finances",
    "My finances control my life",
    "Whenever I feel in control of my finances, something happens that sets me back",
    "I am unable to enjoy life because I obsess too much about money"
]

df_cleaned = df.drop(columns=pertanyaan_columns, errors='ignore')

# 3️⃣ Gabungkan df_cleaned dengan dashboard_df (kolom skor baru)
df_final = pd.concat([df_cleaned, dashboard_df], axis=1)

# 4️⃣ Lihat hasil
print(df_final.head())
print(df_final.columns)

   Gender Province of Origin Random_Code Residence Status    Last Education  \
0  Female      West Sumatera        B99Z     Family House  Diploma I/II/III
1  Female      West Sumatera        A96P   Parent’s House  Diploma I/II/III
2  Female      West Sumatera        C77Q   Parent’s House  Diploma I/II/III
3  Female      West Sumatera        C77Q   Parent’s House  Diploma I/II/III
4  Female      West Sumatera        B99Z   Parent’s House  Diploma I/II/III

                  Job Marital Status  Year of Birth Est. Monthly Income  \
0             Student    Not Married           2000       < Rp2.000.000
1             Student    Not Married           2000       < Rp2.000.000
2  Civil Servant/BUMN    Not Married           2000       < Rp2.000.000
3             Student    Not Married           2000       < Rp2.000.000
4             Student    Not Married           2000       < Rp2.000.000

  Est. Monthly Expenditure  ...  Financial_Knowledge_Score  \
0            < Rp2.000.000  ...                        3.4
1            < Rp2.000.000  ...                        2.9
2            < Rp2.000.000  ...                        3.1
3            < Rp2.000.000  ...                        2.8
4            < Rp2.000.000  ...                        3.2

   Fintech_Literacy_Score  Financial_Behavior_Score  Financial_Decision_Score  \
0                     2.4                       3.1                       2.7
1                     3.2                       3.0                       2.6
2                     2.6                       2.9                       2.7
3                     2.4                       2.7                       2.5
4                     3.8                       3.9                       2.8

   Financial_Wellbeing_Score  Financial_Knowledge_Score  \
0                        2.4                        3.4
1                        2.9                        2.9
2                        2.2                        3.1
3                        2.4                        2.8
4                        2.6                        3.2

   Fintech_Literacy_Score  Financial_Behavior_Score  Financial_Decision_Score  \
0                     2.4                       3.1                       2.7
1                     3.2                       3.0                       2.6
2                     2.6                       2.9                       2.7
3                     2.4                       2.7                       2.5
4                     3.8                       3.9                       2.8

   Financial_Wellbeing_Score
0                        2.4
1                        2.9
2                        2.2
3                        2.4
4                        2.6

[5 rows x 21 columns]
Index(['Gender', 'Province of Origin', 'Random_Code', 'Residence Status',
       'Last Education', 'Job', 'Marital Status', 'Year of Birth',
       'Est. Monthly Income', 'Est. Monthly Expenditure',
       'I will achieve the financial goals that I have set for myself',
       'Financial_Knowledge_Score', 'Fintech_Literacy_Score',
       'Financial_Behavior_Score', 'Financial_Decision_Score',
       'Financial_Wellbeing_Score', 'Financial_Knowledge_Score',
       'Fintech_Literacy_Score', 'Financial_Behavior_Score',
       'Financial_Decision_Score', 'Financial_Wellbeing_Score'],
      dtype='object')

In [ ]:
df_final.duplicated().sum()

np.int64(3)

In [ ]:
duplicate_rows_final = df_final[df_final.duplicated(keep=False)]
display(duplicate_rows_final)

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,...,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
259,Pria,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2001,< Rp2.000.000,< Rp2.000.000,...,2.9,3.0,2.9,3.0,3.0,2.9,3.0,2.9,3.0,3.0
620,Pria,Central Java,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,...,3.0,3.0,3.0,2.8,2.9,3.0,3.0,3.0,2.8,2.9
659,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Unknown,...,3.7,3.6,3.4,2.9,2.4,3.7,3.6,3.4,2.9,2.4
663,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Unknown,...,3.7,3.6,3.4,2.9,2.4,3.7,3.6,3.4,2.9,2.4
1636,Pria,Central Java,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,...,3.0,3.0,3.0,2.8,2.9,3.0,3.0,3.0,2.8,2.9
1642,Pria,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2001,< Rp2.000.000,< Rp2.000.000,...,2.9,3.0,2.9,3.0,3.0,2.9,3.0,2.9,3.0,3.0

In [ ]:
print("Nilai unik dari kolom 'Gender':")
print(df_final['Gender'].unique())

Nilai unik dari kolom 'Gender':
['Female' 'Male' 'F' 'M' 'Wanita' 'Pria' 'Unknown']

In [ ]:
# Normalisasi nilai Gender
df_final['Gender'] = df_final['Gender'].replace({
    'F': 'Female',
    'M': 'Male',
    'Wanita': 'Female',
    'Pria': 'Male'
})

# Pastikan semua huruf kapitalisasi konsisten (opsional)
df_final['Gender'] = df_final['Gender'].str.title()

# Cek hasil
print("Nilai unik setelah normalisasi:", df_final['Gender'].unique())

Nilai unik setelah normalisasi: ['Female' 'Male' 'Unknown']

In [ ]:
df_final.isnull().sum()

Gender                                                           0
Province of Origin                                               0
Random_Code                                                      0
Residence Status                                                 0
Last Education                                                   0
Job                                                              0
Marital Status                                                   0
Year of Birth                                                    0
Est. Monthly Income                                              0
Est. Monthly Expenditure                                         0
I will achieve the financial goals that I have set for myself    0
Financial_Knowledge_Score                                        0
Fintech_Literacy_Score                                           0
Financial_Behavior_Score                                         0
Financial_Decision_Score                                         0
Financial_Wellbeing_Score                                        0
Financial_Knowledge_Score                                        0
Fintech_Literacy_Score                                           0
Financial_Behavior_Score                                         0
Financial_Decision_Score                                         0
Financial_Wellbeing_Score                                        0
dtype: int64

In [ ]:
df_final

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,...,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3.4,2.4,3.1,2.7,2.4,3.4,2.4,3.1,2.7,2.4
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,2.9,3.2,3.0,2.6,2.9,2.9,3.2,3.0,2.6,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3.1,2.6,2.9,2.7,2.2,3.1,2.6,2.9,2.7,2.2
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,2.8,2.4,2.7,2.5,2.4,2.8,2.4,2.7,2.5,2.4
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3.2,3.8,3.9,2.8,2.6,3.2,3.8,3.9,2.8,2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1646,Male,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2000,Unknown,< Rp2.000.000,...,3.3,2.2,3.3,3.0,1.6,3.3,2.2,3.3,3.0,1.6
1647,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,...,2.2,2.4,2.7,2.8,2.4,2.2,2.4,2.7,2.8,2.4
1649,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Rp2.000.001 – Rp4.000.000,...,1.7,3.1,2.6,2.7,2.1,1.7,3.1,2.6,2.7,2.1
1650,Female,DI Yogyakarta,Unknown,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Unknown,< Rp2.000.000,...,2.8,3.3,2.6,2.9,2.4,2.8,3.3,2.6,2.9,2.4
1651,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,...,2.6,2.7,2.3,2.6,3.0,2.6,2.7,2.3,2.6,3.0

In [ ]:
# Simpan ke file Excel
output_path = "/content/Gen_Z_Financial_Literacy_Survey_clean.csv"  # ubah path sesuai kebutuhan kamu
df_final.to_csv(output_path, index=False)

print(f"✅ Dataset berhasil disimpan ke: {output_path}")

✅ Dataset berhasil disimpan ke: /content/Gen_Z_Financial_Literacy_Survey_clean.csv

In [ ]:
df1 = pd.read_csv("/content/drive/MyDrive/GELAR RASA/Dataset/GenZ_Financial_Score.csv")
df1.head()

,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,3.4,2.4,3.1,2.7,2.4
1,2.9,3.2,3.0,2.6,2.9
2,3.1,2.6,2.9,2.7,2.3
3,2.8,2.4,2.7,2.5,2.4
4,3.2,3.8,3.9,2.8,2.7

In [ ]:
df_clean = df.drop(df.columns[10:58],axis=1)

In [ ]:
df_concat = pd.concat([df_clean, df1], axis=1)
display(df_concat)

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.4,2.4,3.1,2.7,2.4
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.9,3.2,3.0,2.6,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,3.1,2.6,2.9,2.7,2.3
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.8,2.4,2.7,2.5,2.4
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.2,3.8,3.9,2.8,2.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,2.2,2.4,2.7,2.8,2.4
1648,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,NaN,3.7,3.6,3.4,2.9,2.4
1649,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,1.7,3.1,2.6,2.7,2.2
1650,Female,DI Yogyakarta,NaN,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,NaN,< Rp2.000.000,2.8,3.3,2.6,2.9,2.6
1651,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,2.6,2.7,2.3,2.6,3.1

In [ ]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1652 entries, 0 to 1651
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Gender                     1538 non-null   object
 1   Province of Origin         1652 non-null   object
 2   Random_Code                1234 non-null   object
 3   Residence Status           1652 non-null   object
 4   Last Education             1652 non-null   object
 5   Job                        1652 non-null   object
 6   Marital Status             1652 non-null   object
 7   Year of Birth              1652 non-null   int64
 8   Est. Monthly Income        1535 non-null   object
 9   Est. Monthly Expenditure   1537 non-null   object
 10  Financial_Knowledge_Score  1652 non-null   float64
 11  Fintech_Literacy_Score     1652 non-null   float64
 12  Financial_Behavior_Score   1652 non-null   float64
 13  Financial_Decision_Score   1652 non-null   float64
 14  Financial_Wellbeing_Score  1652 non-null   float64
dtypes: float64(5), int64(1), object(9)
memory usage: 193.7+ KB

In [ ]:
columns_to_check = ['Gender', 'Province of Origin', 'Residence Status', 'Last Education', 'Job', 'Marital Status', 'Year of Birth', 'Est. Monthly Income', 'Est. Monthly Expenditure']

for col in columns_to_check:
    print(f"Nilai unik dari kolom '{col}':")
    print(df_concat[col].unique())
    print("-" * 30)

Nilai unik dari kolom 'Gender':
['Female' 'Male' 'F' 'M' 'Wanita' 'Pria' nan]
------------------------------
Nilai unik dari kolom 'Province of Origin':
['West Sumatera' 'DKI Jakarta' 'Riau' 'Central Java' 'East Java' 'Bali'
 'West Java' 'Banten' 'Jambi' 'Southeast Sulawesi' 'North Sumatera'
 'South Sumatera' 'Papua' 'Nanggroe Aceh Darussalam' 'Riau Islands'
 'Bengkulu' 'South Kalimantan' 'DI Yogyakarta' 'Lampung' 'North Maluku']
------------------------------
Nilai unik dari kolom 'Residence Status':
['Family House' 'Parent’s House' 'Rental House' 'Boarding House'
 'Own House' 'Dormitory']
------------------------------
Nilai unik dari kolom 'Last Education':
['Diploma I/II/III' 'Senior High School (SMA)' 'Bachelor (S1)/Diploma IV'
 'Postgraduate' 'Junior High School (SMP)' 'Elementary School (SD)']
------------------------------
Nilai unik dari kolom 'Job':
['Student' 'Civil Servant/BUMN' 'Private Employee' 'Others' 'Not Working'
 'Entrepreneur']
------------------------------
Nilai unik dari kolom 'Marital Status':
['Not Married' 'Married']
------------------------------
Nilai unik dari kolom 'Year of Birth':
[2000 1999 1998 2050 2001 2027 1997 2002 2003 2004 2005 1901 2007 2008
 2012 2009 2011 2010 2006]
------------------------------
Nilai unik dari kolom 'Est. Monthly Income':
['< Rp2.000.000' 'Rp2.000.001 – Rp4.000.000' 'Rp4.000.001 – Rp6.000.000'
 nan 'Rp.2.000.001 â€“ Rp.4.000.000' 'Rp6.000.001 – Rp10.000.000'
 'Rp10.000.001 – Rp15.000.000' '< Rp.2.000.000' '> Rp15.000.000'
 'Rp.6.000.001 â€“ Rp.10.000.000' 'Rp.4.000.001 â€“ Rp.6.000.000']
------------------------------
Nilai unik dari kolom 'Est. Monthly Expenditure':
['< Rp2.000.000' 'Rp4.000.001 – Rp6.000.000' 'Rp2.000.001 – Rp4.000.000'
 nan 'Rp6.000.001 – Rp10.000.000' 'Rp10.000.001 – Rp15.000.000']
------------------------------

# Penanganan Missing Value Gender

In [ ]:
# Tangani missing value pada kolom Gender dan standardisasi nilai
df_concat['Gender'] =df_concat['Gender'].replace(['F', 'Wanita'], 'Female')
df_concat['Gender'] =df_concat['Gender'].replace(['M', 'Pria'], 'Male')
df_concat['Gender'] =df_concat['Gender'].fillna('Unknown')

# Cek hasilnya
print("Jumlah missing value pada kolom Gender setelah imputasi:",df_concat['Gender'].isna().sum())
print(df_concat['Gender'].value_counts(dropna=False))

Jumlah missing value pada kolom Gender setelah imputasi: 0
Gender
Female     996
Male       542
Unknown    114
Name: count, dtype: int64

In [ ]:
# Pastikan semua nilai jadi string dulu
df_concat['Est. Monthly Income'] = df_concat['Est. Monthly Income'].astype(str)

# Bersihkan karakter aneh dan ubah tanda hubung jadi normal
df_concat['Est. Monthly Income'] = (
    df_concat['Est. Monthly Income']
    .replace({'â€“': '–', 'Ã¢â‚¬â€œ': '–'}, regex=True)  # berbagai variasi dash error
    .replace({r'[^\x00-\x7F]+': '–'}, regex=True)  # hapus karakter non-ASCII
    .str.strip()
)
df_concat['Est. Monthly Income'] = df_concat['Est. Monthly Income'].replace({
    '< Rp.2.000.000': '< Rp2.000.000',
    'Rp.2.000.001 – Rp.4.000.000' :  'Rp2.000.001 – Rp4.000.000',
    'Rp.4.000.001 – Rp.6.000.000' :  'Rp4.000.001 – Rp6.000.000',
    'Rp.6.000.001 – Rp.10.000.000' : 'Rp6.000.001 – Rp10.000.000'
})

# Lihat hasilnya
print("Nilai unik sesudah dibersihkan:")
print(df_concat['Est. Monthly Income'].unique())

Nilai unik sesudah dibersihkan:
['< Rp2.000.000' 'Rp2.000.001 – Rp4.000.000' 'Rp4.000.001 – Rp6.000.000'
 'nan' 'Rp6.000.001 – Rp10.000.000' 'Rp10.000.001 – Rp15.000.000'
 '> Rp15.000.000']

In [ ]:
df_concat['Est. Monthly Income'] = (
    df_concat['Est. Monthly Income']
    .replace({'nan': 'Unknown', 'NaN': 'Unknown'}, regex=False)
    .fillna('Unknown')
)
print(df_concat['Est. Monthly Income'].value_counts(dropna=False))

Est. Monthly Income
< Rp2.000.000                  1111
Rp2.000.001 – Rp4.000.000       286
Unknown                         117
Rp4.000.001 – Rp6.000.000        92
Rp6.000.001 – Rp10.000.000       28
Rp10.000.001 – Rp15.000.000      12
> Rp15.000.000                    6
Name: count, dtype: int64

In [ ]:
df_concat['Est. Monthly Expenditure'] = (
    df_concat['Est. Monthly Expenditure']
    .replace({'nan': 'Unknown', 'NaN': 'Unknown'}, regex=False)
    .fillna('Unknown')
)
print(df_concat['Est. Monthly Expenditure'].value_counts(dropna=False))

Est. Monthly Expenditure
< Rp2.000.000                  1174
Rp2.000.001 – Rp4.000.000       305
Unknown                         115
Rp4.000.001 – Rp6.000.000        48
Rp6.000.001 – Rp10.000.000        8
Rp10.000.001 – Rp15.000.000       2
Name: count, dtype: int64

# feature engineer numeric

In [ ]:
pd.options.display.float_format = '{:.1f}'.format

In [ ]:
df_concat.head()

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.4,2.4,3.1,2.7,2.4
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.9,3.2,3.0,2.6,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,3.1,2.6,2.9,2.7,2.3
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.8,2.4,2.7,2.5,2.4
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.2,3.8,3.9,2.8,2.7

## Cleaning

In [ ]:
df_concat.duplicated().sum()

np.int64(21)

In [ ]:
duplicate_rows_concat = df_concat[df_concat.duplicated(keep=False)]
display(duplicate_rows_concat)

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
259,Male,West Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2001,< Rp2.000.000,< Rp2.000.000,2.9,3.0,2.9,3.0,3.0
390,Female,West Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2005,< Rp2.000.000,< Rp2.000.000,2.9,2.9,2.7,2.9,2.9
391,Female,West Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2005,< Rp2.000.000,< Rp2.000.000,2.9,2.9,2.7,2.9,2.9
620,Male,Central Java,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,3.0,3.0,3.0,2.8,2.9
636,Male,DKI Jakarta,A12X,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2002,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,3.0,3.2,3.3,3.1,3.2
639,Male,DKI Jakarta,A12X,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2002,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,3.0,3.2,3.3,3.1,3.2
645,Female,DI Yogyakarta,NaN,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
646,Female,DI Yogyakarta,NaN,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
647,Female,DI Yogyakarta,B99Z,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
648,Female,Central Java,A12X,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Rp4.000.001 – Rp6.000.000,< Rp2.000.000,3.6,3.6,3.3,3.0,2.8
649,Female,DI Yogyakarta,C77Q,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
650,Female,Central Java,NaN,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Rp4.000.001 – Rp6.000.000,< Rp2.000.000,3.6,3.6,3.3,3.0,2.8
651,Female,Central Java,A12X,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Rp4.000.001 – Rp6.000.000,< Rp2.000.000,3.6,3.6,3.3,3.0,2.8
653,Male,DKI Jakarta,B99Z,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,3.0,3.2,3.3,3.1,3.1
654,Female,Central Java,A12X,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Rp4.000.001 – Rp6.000.000,< Rp2.000.000,3.6,3.6,3.3,3.0,2.8
655,Female,DI Yogyakarta,B99Z,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
658,Female,DI Yogyakarta,B99Z,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
659,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,Unknown,3.7,3.6,3.4,2.9,2.4
661,Female,Central Java,NaN,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Rp4.000.001 – Rp6.000.000,< Rp2.000.000,3.6,3.6,3.3,3.0,2.8
663,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,Unknown,3.7,3.6,3.4,2.9,2.4
664,Male,DKI Jakarta,B99Z,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,Rp2.000.001 – Rp4.000.000,3.0,3.2,3.3,3.1,3.1
666,Female,DI Yogyakarta,C77Q,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
670,Female,DI Yogyakarta,NaN,Family House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.7,3.4,3.3,3.2,2.9
687,Male,DKI Jakarta,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,Unknown,2.6,2.2,2.5,2.7,2.2
701,Male,North Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.4,3.3,3.3,3.2,3.2
704,Male,North Sumatera,A12X,Parent’s House,Senior High School (SMA),Student,Not Married,2005,< Rp2.000.000,< Rp2.000.000,3.6,3.3,3.4,3.1,2.7
705,Male,North Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2005,< Rp2.000.000,< Rp2.000.000,3.3,3.1,3.1,2.9,3.4
709,Male,North Sumatera,A12X,Parent’s House,Senior High School (SMA),Student,Not Married,2005,< Rp2.000.000,< Rp2.000.000,3.6,3.3,3.4,3.1,2.7
713,Male,North Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2005,< Rp2.000.000,< Rp2.000.000,3.3,3.1,3.1,2.9,3.4
714,Male,North Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,Rp2.000.001 – Rp4.000.000,3.4,3.3,3.3,3.2,3.2
733,Female,North Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,3.3,3.2,3.3,2.9,2.8
737,Female,North Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp2.000.001 – Rp4.000.000,< Rp2.000.000,3.3,3.2,3.3,2.9,2.8
1267,Female,Central Java,B99Z,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,< Rp2.000.000,Rp2.000.001 – Rp4.000.000,2.9,2.4,2.4,2.3,3.4
1633,Female,Central Java,B99Z,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,< Rp2.000.000,Rp2.000.001 – Rp4.000.000,2.9,2.4,2.4,2.3,3.4
1635,Male,DKI Jakarta,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,Unknown,2.6,2.2,2.5,2.7,2.2
1636,Male,Central Java,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,3.0,3.0,3.0,2.8,2.9
1642,Male,West Sumatera,NaN,Parent’s House,Senior High School (SMA),Student,Not Married,2001,< Rp2.000.000,< Rp2.000.000,2.9,3.0,2.9,3.0,3.0
1648,Female,North Sumatera,C77Q,Rental House,Bachelor (S1)/Diploma IV,Student,Not Married,2004,Rp4.000.001 – Rp6.000.000,Unknown,3.7,3.6,3.4,2.9,2.4

In [ ]:
df_concat.drop_duplicates(inplace=True)
df_concat.reset_index(drop=True, inplace=True)

In [ ]:
# hapus kolom random_code
df_concat.drop('Random_Code', axis=1, inplace=True)

In [ ]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1631 entries, 0 to 1630
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Gender                     1631 non-null   object
 1   Province of Origin         1631 non-null   object
 2   Residence Status           1631 non-null   object
 3   Last Education             1631 non-null   object
 4   Job                        1631 non-null   object
 5   Marital Status             1631 non-null   object
 6   Year of Birth              1631 non-null   int64
 7   Est. Monthly Income        1631 non-null   object
 8   Est. Monthly Expenditure   1631 non-null   object
 9   Financial_Knowledge_Score  1631 non-null   float64
 10  Fintech_Literacy_Score     1631 non-null   float64
 11  Financial_Behavior_Score   1631 non-null   float64
 12  Financial_Decision_Score   1631 non-null   float64
 13  Financial_Wellbeing_Score  1631 non-null   float64
dtypes: float64(5), int64(1), object(8)
memory usage: 178.5+ KB

In [ ]:
df_concat.isnull().sum()

Gender                       0
Province of Origin           0
Residence Status             0
Last Education               0
Job                          0
Marital Status               0
Year of Birth                0
Est. Monthly Income          0
Est. Monthly Expenditure     0
Financial_Knowledge_Score    0
Fintech_Literacy_Score       0
Financial_Behavior_Score     0
Financial_Decision_Score     0
Financial_Wellbeing_Score    0
dtype: int64

In [ ]:
# Simpan ke file CSV
df_concat.to_csv("financial literacy_clean.csv", index=False)

# Unduh file ke komputer (jika di Google Colab)
from google.colab import files
files.download("financial literacy_clean.csv")

# Data "Gen Z Financial Profile"

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/GELAR RASA/Dataset/GenZ_Financial_Profile.csv", sep=';')
df2

    user_id ID  birth_year  gender                   province  \
0        U0001        2001    Male          Kalimantan Tengah
1        U0002        2007  Female              Papua Selatan
2        U0003        2011  Female           Sulawesi Selatan
3        U0004        2009  Female                  Gorontalo
4        U0005        2010    Male           Kalimantan Barat
5        U0006        2008    Male             Sulawesi Utara
6        U0007        2009    Male           Sumatera Selatan
7        U0008        2011  Female           Papua Pegunungan
8        U0009        2002  Female             Sumatera Utara
9        U0010        2006  Female         Kalimantan Selatan
10       U0011        2001    Male               Maluku Utara
11       U0012        2012  Female                     Banten
12       U0013        2012  Female        Nusa Tenggara Barat
13       U0014        1997    Male                      Jambi
14       U0015        2009    Male           Papua Pegunungan
15       U0016        2012    Male             Sulawesi Barat
16       U0017        2000    Male        Nusa Tenggara Timur
17       U0018        2007  Female           Kalimantan Timur
18       U0019        2011    Male                      Papua
19       U0020        1997    Male                Jawa Tengah
20       U0021        2009  Female                  Gorontalo
21       U0022        2003    Male           Papua Pegunungan
22       U0023        2012    Male         Kalimantan Selatan
23       U0024        2012    Male           Papua Pegunungan
24       U0025        2012    Male  Kepulauan Bangka Belitung
25       U0026        2005  Female        Nusa Tenggara Timur
26       U0027        2011    Male           Papua Barat Daya
27       U0028        2011  Female           Sumatera Selatan
28       U0029        2003  Female                 Jawa Timur
29       U0030        2010    Male           Kalimantan Barat
30       U0031        1997  Female  Kepulauan Bangka Belitung
31       U0032        2007    Male               Maluku Utara
32       U0033        2001    Male                       Riau
33       U0034        1999  Female        Nusa Tenggara Barat
34       U0035        1998  Female                      Jambi
35       U0036        2009  Female           Kalimantan Barat
36       U0037        2003    Male           Kalimantan Timur
37       U0038        2009    Male                DKI Jakarta
38       U0039        1998  Female              Papua Selatan
39       U0040        2003    Male         Kalimantan Selatan
40       U0041        2006    Male                       Riau
41       U0042        2010    Male                  Gorontalo
42       U0043        2003    Male                      Papua
43       U0044        2008  Female                Jawa Tengah
44       U0045        2011    Male  Kepulauan Bangka Belitung
45       U0046        2008  Female                     Maluku
46       U0047        2001    Male                   Bengkulu
47       U0048        1997  Female                       Riau
48       U0049        2011  Female        Nusa Tenggara Timur
49       U0050        1997    Male             Sulawesi Barat
50       U0051        2011  Female                     Maluku
51       U0052        2006  Female               Papua Tengah
52       U0053        2012  Female          Kalimantan Tengah
53       U0054        2010  Female                     Maluku
54       U0055        2012  Female        Nusa Tenggara Timur
55       U0056        2004  Female                     Maluku
56       U0057        2010    Male               Maluku Utara
57       U0058        2004    Male             Sumatera Utara
58       U0059        2006    Male             Kepulauan Riau
59       U0060        2008    Male             Sumatera Utara
60       U0061        2011    Male             Sumatera Utara
61       U0062        2012    Male           Kalimantan Utara
62       U0063        2010  Female                       Bali
63       U0064        2005    Male               Maluku Utara
64       U0065        2005    Male                     Banten
65       U0066        2009  Female                     Banten
66       U0067        2002    Male                     Maluku
67       U0068        1999  Female           Kalimantan Utara
68       U0069        2004    Male                       Aceh
69       U0070        2002  Female                DKI Jakarta
70       U0071        2003  Female          Kalimantan Tengah
71       U0072        2001    Male                       Riau
72       U0073        1998    Male                   Bengkulu
73       U0074        1997  Female            Sulawesi Tengah
74       U0075        2012  Female                 Jawa Barat
75       U0076        2005  Female                     Maluku
76       U0077        2004  Female                       Bali
77       U0078        2008    Male                Papua Barat
78       U0079        2001    Male                DKI Jakarta
79       U0080        2012    Male          Sulawesi Tenggara
80       U0081        2010  Female               Maluku Utara
81       U0082        1999  Female                       Aceh
82       U0083        2005    Male          Sulawesi Tenggara
83       U0084        2011    Male                   Bengkulu
84       U0085        2012    Male             Sumatera Utara
85       U0086        2005    Male           Kalimantan Utara
86       U0087        2008  Female                       Riau
87       U0088        2000  Female        Nusa Tenggara Timur
88       U0089        2012  Female            Sulawesi Tengah
89       U0090        2001    Male                DKI Jakarta
90       U0091        2012    Male                DKI Jakarta
91       U0092        2008  Female             Sumatera Barat
92       U0093        2007  Female                 Jawa Barat
93       U0094        2006  Female             Sumatera Barat
94       U0095        2001  Female           Sulawesi Selatan
95       U0096        2000    Male             Sumatera Utara
96       U0097        2001  Female                     Banten
97       U0098        2001    Male             Sumatera Utara
98       U0099        2010    Male             Sulawesi Barat
99       U0100        2004    Male           Kalimantan Barat
100      U0101        1998    Male           Papua Barat Daya
101      U0102        2012  Female          Sulawesi Tenggara
102      U0103        2011    Male             Sulawesi Utara
103      U0104        2012  Female               Maluku Utara
104      U0105        2012  Female             Kepulauan Riau
105      U0106        2000    Male                Papua Barat
106      U0107        2004    Male                Jawa Tengah
107      U0108        2009  Female              Papua Selatan
108      U0109        2009    Male                     Banten
109      U0110        2000    Male         Kalimantan Selatan
110      U0111        2010    Male           Kalimantan Barat
111      U0112        2001    Male           Sulawesi Selatan
112      U0113        2001  Female                     Banten
113      U0114        2006  Female                      Papua
114      U0115        2007  Female               Maluku Utara
115      U0116        2007  Female            Sulawesi Tengah
116      U0117        1999  Female             Sulawesi Utara
117      U0118        2011    Male             Sumatera Utara
118      U0119        2002  Female                 Jawa Barat
119      U0120        1999  Female  Kepulauan Bangka Belitung
120      U0121        2011  Female                 Jawa Barat
121      U0122        2012  Female            Sulawesi Tengah
122      U0123        2011    Male  Kepulauan Bangka Belitung
123      U0124        2010    Male             Kepulauan Riau
124      U0125        2008    Male               Maluku Utara
125      U0126        2007    Male                      Papua
126      U0127        1999  Female           Kalimantan Barat
127      U0128        2004  Female             Sumatera Utara
128      U0129        2004    Male                       Aceh
129      U0130        2002  Female           Papua Pegunungan
130      U0131        2009    Male           Kalimantan Utara
131      U0132        2006    Male           Sulawesi Selatan
132      U0133        1998    Male             Sumatera Utara
133      U0134        2001    Male                     Maluku
134      U0135        2008  Female              DI Yogyakarta
135      U0136        1998    Male             Sumatera Utara
136      U0137        2011  Female                  Gorontalo
137      U0138        2006  Female                 Jawa Timur
138      U0139        2006    Male                 Jawa Barat
139      U0140        2007  Female              Papua Selatan
140      U0141        2010  Female          Sulawesi Tenggara
141      U0142        2003    Male           Kalimantan Barat
142      U0143        2008    Male           Kalimantan Utara
143      U0144        2007    Male          Kalimantan Tengah
144      U0145        2002    Male             Kepulauan Riau
145      U0146        2011    Male              DI Yogyakarta
146      U0147        2010  Female              Papua Selatan
147      U0148        2008    Male        Nusa Tenggara Barat
148      U0149        2011    Male           Kalimantan Utara
149      U0150        2011    Male              DI Yogyakarta
150      U0151        2009  Female                      Papua
151      U0152        2011    Male                 Jawa Barat
152      U0153        2009    Male         Kalimantan Selatan
153      U0154        2008    Male           Sumatera Selatan
154      U0155        2008  Female           Papua Pegunungan
155      U0156        2009    Male           Papua Pegunungan
156      U0157        2000  Female         Kalimantan Selatan
157      U0158        2011  Female              DI Yogyakarta
158      U0159        2011    Male                     Banten
159      U0160        1997  Female           Papua Pegunungan
160      U0161        2010    Male             Sulawesi Utara
161      U0162        1999  Female               Maluku Utara
162      U0163        2003  Female                Papua Barat
163      U0164        2009  Female           Papua Pegunungan
164      U0165        2000    Male           Kalimantan Barat
165      U0166        2010  Female        Nusa Tenggara Barat
166      U0167        2010    Male           Papua Barat Daya
167      U0168        2006    Male             Sumatera Barat
168      U0169        1997    Male           Kalimantan Timur
169      U0170        2002  Female               Maluku Utara
170      U0171        2008  Female                     Banten
171      U0172        2012    Male                      Jambi
172      U0173        2008  Female                       Riau
173      U0174        2002    Male          Kalimantan Tengah
174      U0175        2008  Female              DI Yogyakarta
175      U0176        2006    Male                     Maluku
176      U0177        2010  Female              DI Yogyakarta
177      U0178        1999    Male           Sumatera Selatan
178      U0179        2010  Female                 Jawa Barat
179      U0180        2006    Male                     Banten
180      U0181        2012    Male                       Bali
181      U0182        2003    Male           Kalimantan Timur
182      U0183        2008  Female              DI Yogyakarta
183      U0184        2012  Female                   Bengkulu
184      U0185        1999    Male               Maluku Utara
185      U0186        2012  Female                 Jawa Timur
186      U0187        2009  Female                       Bali
187      U0188        1998  Female                      Papua
188      U0189        2003  Female                      Jambi
189      U0190        2009    Male           Sulawesi Selatan
190      U0191        1998    Male           Kalimantan Timur
191      U0192        2007  Female              DI Yogyakarta
192      U0193        2003  Female                 Jawa Timur
193      U0194        2008  Female                Papua Barat
194      U0195        1998    Male                     Maluku
195      U0196        2011    Male               Papua Tengah
196      U0197        2012  Female                       Bali
197      U0198        2012  Female          Sulawesi Tenggara
198      U0199        2009  Female        Nusa Tenggara Timur
199      U0200        1999  Female           Kalimantan Timur
200      U0201        2009  Female               Maluku Utara
201      U0202        1997    Male                Jawa Tengah
202      U0203        1997    Male           Kalimantan Barat
203      U0204        2003  Female               Papua Tengah
204      U0205        2006  Female                      Jambi
205      U0206        2010    Male  Kepulauan Bangka Belitung
206      U0207        2008    Male                  Gorontalo
207      U0208        2005  Female           Sumatera Selatan
208      U0209        2002    Male             Sulawesi Utara
209      U0210        2012    Male                     Maluku
210      U0211        2005  Female         Kalimantan Selatan
211      U0212        2005  Female             Sumatera Utara
212      U0213        2000  Female                      Jambi
213      U0214        2010    Male           Sulawesi Selatan
214      U0215        2009  Female             Sulawesi Utara
215      U0216        2001    Male                    Lampung
216      U0217        1998    Male                       Aceh
217      U0218        2008  Female           Kalimantan Barat
218      U0219        2008  Female           Kalimantan Timur
219      U0220        2002  Female               Maluku Utara
220      U0221        2012  Female                DKI Jakarta
221      U0222        2000  Female           Kalimantan Utara
222      U0223        2005    Male                DKI Jakarta
223      U0224        2012    Male                  Gorontalo
224      U0225        2005    Male            Sulawesi Tengah
225      U0226        2008    Male                     Banten
226      U0227        2004  Female               Papua Tengah
227      U0228        2002    Male           Kalimantan Barat
228      U0229        2012  Female             Sumatera Barat
229      U0230        2004  Female                       Aceh
230      U0231        2011  Female                       Aceh
231      U0232        2001    Male                       Bali
232      U0233        2001  Female             Sumatera Utara
233      U0234        1997    Male                  Gorontalo
234      U0235        2008    Male           Kalimantan Barat
235      U0236        2004  Female           Sumatera Selatan
236      U0237        2011    Male                    Lampung
237      U0238        2005    Male                  Gorontalo
238      U0239        2012  Female                Papua Barat
239      U0240        2001    Male             Sumatera Barat
240      U0241        2011  Female               Papua Tengah
241      U0242        2010  Female                      Jambi
242      U0243        2010  Female           Sulawesi Selatan
243      U0244        2011    Male                 Jawa Barat
244      U0245        2010    Male           Kalimantan Barat
245      U0246        2008  Female           Kalimantan Barat
246      U0247        1999    Male  Kepulauan Bangka Belitung
247      U0248        1997  Female                       Riau
248      U0249        2012  Female        Nusa Tenggara Timur
249      U0250        2008  Female           Papua Barat Daya
250      U0251        2010    Male           Sulawesi Selatan
251      U0252        2006    Male                Jawa Tengah
252      U0253        1999  Female                Jawa Tengah
253      U0254        1999    Male         Kalimantan Selatan
254      U0255        2009    Male          Sulawesi Tenggara
255      U0256        2005  Female         Kalimantan Selatan
256      U0257        2001  Female        Nusa Tenggara Timur
257      U0258        2006  Female                    Lampung
258      U0259        1998  Female                    Lampung
259      U0260        2007    Male            Sulawesi Tengah
260      U0261        2002  Female            Sulawesi Tengah
261      U0262        2010  Female           Kalimantan Timur
262      U0263        2003    Male                Jawa Tengah
263      U0264        2005  Female          Sulawesi Tenggara
264      U0265        1997  Female  Kepulauan Bangka Belitung
265      U0266        1998  Female           Kalimantan Barat
266      U0267        2004  Female        Nusa Tenggara Timur
267      U0268        2006  Female                 Jawa Barat
268      U0269        2007    Male                 Jawa Timur
269      U0270        2002    Male                     Maluku
270      U0271        2009  Female              DI Yogyakarta
271      U0272        2011  Female                DKI Jakarta
272      U0273        2010  Female            Sulawesi Tengah
273      U0274        1997  Female           Sulawesi Selatan
274      U0275        2006  Female                DKI Jakarta
275      U0276        1999    Male           Papua Barat Daya
276      U0277        2002  Female                      Papua
277      U0278        2012  Female        Nusa Tenggara Timur
278      U0279        2000  Female           Sumatera Selatan
279      U0280        2006  Female           Papua Barat Daya
280      U0281        2008  Female          Sulawesi Tenggara
281      U0282        2009    Male                       Aceh
282      U0283        2007    Male               Papua Tengah
283      U0284        1997    Male                    Lampung
284      U0285        2003  Female                   Bengkulu
285      U0286        2006    Male                DKI Jakarta
286      U0287        1999    Male                       Riau
287      U0288        2004  Female             Sulawesi Utara
288      U0289        1997    Male                 Jawa Barat
289      U0290        1998  Female            Sulawesi Tengah
290      U0291        2004    Male           Papua Barat Daya
291      U0292        1999    Male                 Jawa Barat
292      U0293        2007  Female              Papua Selatan
293      U0294        2009    Male           Kalimantan Utara
294      U0295        2010    Male                     Banten
295      U0296        2001  Female                Jawa Tengah
296      U0297        2000  Female             Sulawesi Utara
297      U0298        1999    Male                       Riau
298      U0299        2008  Female                DKI Jakarta
299      U0300        2009    Male               Maluku Utara
300      U0301        1997    Male                   Bengkulu
301      U0302        2012  Female                DKI Jakarta
302      U0303        1998  Female          Sulawesi Tenggara
303      U0304        2006  Female           Kalimantan Timur
304      U0305        2009  Female           Kalimantan Timur
305      U0306        2011  Female          Sulawesi Tenggara
306      U0307        2009  Female            Sulawesi Tengah
307      U0308        2010    Male             Sulawesi Utara
308      U0309        2003  Female                  Gorontalo
309      U0310        2010    Male        Nusa Tenggara Timur
310      U0311        1998    Male                Papua Barat
311      U0312        2011    Male           Papua Pegunungan
312      U0313        2007    Male              DI Yogyakarta
313      U0314        2010  Female              DI Yogyakarta
314      U0315        2005  Female               Papua Tengah
315      U0316        2008  Female             Sulawesi Barat
316      U0317        2006    Male          Sulawesi Tenggara
317      U0318        2009    Male                       Bali
318      U0319        1998    Male             Sumatera Barat
319      U0320        1998    Male                     Banten
320      U0321        2002  Female             Sulawesi Barat

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user_id ID                  1000 non-null   object
 1   birth_year                  1000 non-null   int64
 2   gender                      1000 non-null   object
 3   province                    1000 non-null   object
 4   education_level             1000 non-null   object
 5   employment_status           1000 non-null   object
 6   avg_monthly_income          967 non-null    object
 7   avg_monthly_expense         973 non-null    object
 8   main_fintech_app            1000 non-null   object
 9   ewallet_spending            1000 non-null   object
 10  investment_type             881 non-null    object
 11  loan_usage_purpose          970 non-null    object
 12  outstanding_loan            970 non-null    float64
 13  financial_anxiety_score     1000 non-null   int64
 14  digital_time_spent_per_day  1000 non-null   float64
dtypes: float64(2), int64(2), object(11)
memory usage: 117.3+ KB

In [ ]:
df2.duplicated().sum()

np.int64(0)

In [ ]:
df2.isnull().sum()

user_id ID                      0
birth_year                      0
gender                          0
province                        0
education_level                 0
employment_status               0
avg_monthly_income             33
avg_monthly_expense            27
main_fintech_app                0
ewallet_spending                0
investment_type               119
loan_usage_purpose             30
outstanding_loan               30
financial_anxiety_score         0
digital_time_spent_per_day      0
dtype: int64

In [ ]:
df2[df2['avg_monthly_expense'].isna()].head(10)

,user_id ID,birth_year,gender,province,education_level,employment_status,avg_monthly_income,avg_monthly_expense,main_fintech_app,ewallet_spending,investment_type,loan_usage_purpose,outstanding_loan,financial_anxiety_score,digital_time_spent_per_day
37,U0038,2009,Male,DKI Jakarta,Senior High School,Others,< Rp2.000.000,NaN,Dana,Rp500.001 - Rp1.000.000,Kripto,Pendidikan,17558313.0,1,3.3
41,U0042,2010,Male,Gorontalo,Senior High School,Others,Rp4.000.001 - Rp6.000.000,NaN,Kredivo,Rp500.001 - Rp1.000.000,Reksadana,Tidak Ada,0.0,3,6.4
52,U0053,2012,Female,Kalimantan Tengah,Senior High School,Student,< Rp2.000.000,NaN,OVO,< Rp500.000,Reksadana,Tidak Ada,0.0,2,10.6
56,U0057,2010,Male,Maluku Utara,Senior High School,Private Employee,Rp2.000.001 - Rp4.000.000,NaN,Dana,Rp500.001 - Rp1.000.000,Reksadana,Konsumsi,14633059.0,4,6.0
145,U0146,2011,Male,DI Yogyakarta,Bachelor (S1)/Diploma IV,Student,< Rp2.000.000,NaN,OVO,Rp500.001 - Rp1.000.000,NaN,Tidak Ada,0.0,1,11.5
167,U0168,2006,Male,Sumatera Barat,Junior High School,Student,Rp2.000.001 - Rp4.000.000,NaN,Akulaku,Rp1.000.001 - Rp3.000.000,Reksadana,Pendidikan,12190075.0,5,4.9
283,U0284,1997,Male,Lampung,Elementary School,Not Working,Rp2.000.001 - Rp4.000.000,NaN,Dana,< Rp500.000,Reksadana,Konsumsi,NaN,4,7.8
299,U0300,2009,Male,Maluku Utara,Senior High School,Entrepreneur,> Rp15.000.000,NaN,Kredivo,Rp1.000.001 - Rp3.000.000,Reksadana,Konsumsi,16260206.0,2,6.8
414,U0415,2006,Female,Maluku,Senior High School,Entrepreneur,Rp4.000.001 - Rp6.000.000,NaN,GoPay,Rp500.001 - Rp1.000.000,Saham,Usaha,4522610.0,5,4.4
465,U0466,1998,Male,Kalimantan Timur,Senior High School,Private Employee,Rp6.000.001 - Rp10.000.000,NaN,ShopeePay,Rp1.000.001 - Rp3.000.000,NaN,Konsumsi,1663842.0,5,8.0

In [ ]:
# Isi nilai kosong dengan keterangan yang bermakna
df2['investment_type'] = df2['investment_type'].fillna('Tidak Ada')
df2['loan_usage_purpose'] = df2['loan_usage_purpose'].fillna('Tidak Ada')
df2['outstanding_loan'] = df2['outstanding_loan'].fillna(0)
df2['avg_monthly_income'] = df2['avg_monthly_income'].fillna('Unknown')
df2['avg_monthly_expense'] = df2['avg_monthly_expense'].fillna('Unknown')

In [ ]:
df2.isnull().sum()

user_id ID                    0
birth_year                    0
gender                        0
province                      0
education_level               0
employment_status             0
avg_monthly_income            0
avg_monthly_expense           0
main_fintech_app              0
ewallet_spending              0
investment_type               0
loan_usage_purpose            0
outstanding_loan              0
financial_anxiety_score       0
digital_time_spent_per_day    0
dtype: int64

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user_id ID                  1000 non-null   object
 1   birth_year                  1000 non-null   int64
 2   gender                      1000 non-null   object
 3   province                    1000 non-null   object
 4   education_level             1000 non-null   object
 5   employment_status           1000 non-null   object
 6   avg_monthly_income          1000 non-null   object
 7   avg_monthly_expense         1000 non-null   object
 8   main_fintech_app            1000 non-null   object
 9   ewallet_spending            1000 non-null   object
 10  investment_type             1000 non-null   object
 11  loan_usage_purpose          1000 non-null   object
 12  outstanding_loan            1000 non-null   float64
 13  financial_anxiety_score     1000 non-null   int64
 14  digital_time_spent_per_day  1000 non-null   float64
dtypes: float64(2), int64(2), object(11)
memory usage: 117.3+ KB

In [ ]:
# Simpan ke file CSV
df2.to_csv("financial profile_clean.csv", index=False)

# Unduh file ke komputer (jika di Google Colab)
from google.colab import files
files.download("financial profile_clean.csv")

#Data "Regional Economic Indicators"

In [ ]:
df3=pd.read_csv("/content/drive/MyDrive/GELAR RASA/Dataset/Regional_Economic_Indicators.csv", sep=';')
display(df3)

,Provinsi,Jumlah Rekening Penerima Pinjaman Aktif (entitas),Jumlah Dana yang Diberikan (Rp miliar),Jumlah Rekening Pemberi Pinjaman (akun),TWP 90%,Jumlah Penerima Pinjaman (akun),Outstanding Pinjaman (Rp miliar),Jumlah Penduduk (Ribu),PDRB (Ribu Rp),Urbanisasi (%)
0,Banten,1.742.274,"601,94",83.677,"2,73%",1.244.263,"6.226,21","12537,4",70276,"84,9"
1,DKI Jakarta,2.708.907,"20.964,00",9.272.715,"3,56%",2.324.200,"12.838,89",10678,344350,100
2,Jawa Barat,6.818.787,"251,24",143.127,"3,41%",4.705.372,"20.751,93",50759,56080,"89,3"
3,Jawa Tengah,2.637.739,"29,46",59.501,"2,77%",1.553.694,"6.962,05","38233,9",47972,"60,8"
4,DI Yogyakarta,394.247,"7,26",8.228,"3,31%",240.062,"1.207,31","3781,5",51473,"84,1"
5,Jawa Timur,3.048.079,"132,94",44.643,"3,29%",1.895.275,"10.417,68","42089,3",75770,"66,7"
6,Nangrou Aceh Darusalam,102.897,"1,63",615,"0,82%",70.593,"196,9",5626,43782,"43,2"
7,Sumatera Utara,1.036.941,"26,54",26.205,"1,55%",650.944,"3.078,85","15785,8",73575,"68,1"
8,Sumatera Barat,400.529,"1,77",9.358,"2,40%",198.642,"1.398,91","5914,3",57047,"63,8"
9,Riau,542.854,"4,45",4.273,"1,66%",282.437,"1.565,78","2213,5",165350,"41,8"
10,Kepulauan Riau,309.076,"7,83",9.212,"1,80%",180.411,"993,02",10678,161424,"85,3"
11,Kepualauan Bangka Belitung,103.253,"0,91",1.080,"1,60%",54.643,"337,75","1550,8",70194,"67,4"
12,Jambi,273.264,"1,06",1.251,"2,16%",136.402,"864,3","3768,5",86722,"38,2"
13,Sumatera Selatan,577.990,"8,6",4.120,"2,66%",334.613,"1.728,24","8928,5",75132,"40,1"
14,Bengkulu,138.784,"0,36",358,"1,75%",68.108,"478,3",2138,49233,"35,6"
15,Lampung,530.899,"5,15",4.033,"2,81%",284.856,"1.455,80","9522,9",51370,"42,4"
16,Kalimantan Barat,277.057,"4,73",4.654,"1,54%",151.011,"855,65",5766,52703,"47,9"
17,Kalimantan Tengah,162.309,"0,45",506,"1,49%",90.470,"488,58",2845,79320,"52,9"
18,Kalimantan Utara,39.135,"0,15",84,"3,08%",20.761,"133,66","749,4",198429,-
19,Kalimantan Timur,453.429,"6,55",1.311,"1,94%",266.429,"1.309,86","4267,6",212175,"77,7"
20,Kalimantan Selatan,336.953,"2,29",2.214,"2,00%",190.913,"958,78","4323,3",67117,"59,8"
21,Sulawesi Utara,269.034,"0,78",1.493,"1,35%",152.307,"976,3","2721,4",69352,"68,7"
22,Gorontalo,114.275,"0,35",298,"1,40%",51.903,"457,14","1242,2",44433,"58,4"
23,Sulawesi Tengah,177.868,"0,64",665,"1,54%",77.106,"598,93","3156,1",120750,"43,1"
24,Sulawesi Barat,57.874,"0,12",247,"1,19%",25.633,"230,51","1525,3",42718,"23,1"
25,Sulawesi Selatan,609.232,"6,63",7.617,"1,67%",354.031,"2.038,05","9563,1",73573,"59,6"
26,Sulawesi Tenggara,140.184,"0,27",529,"1,44%",69.118,"701,29","2836,7",67840,"48,3"
27,Bali,427.124,"18,54",8.469,"1,13%",260.541,"1.781,63","2836,7",67319,"81,2"
28,Nusa Tenggara Barat,237.629,"1,14",6.378,"4,36%",100.966,"827,06","5731,1",32282,"62,7"
29,Nusa Tenggara Timur,226.040,"0,72",8.249,"1,41%",74.766,"753,13","5742,6",24272,"34,6"
30,Maluku Utara,54.436,"0,08",74,"0,62%",27.649,"242,69","1373,8",70660,"30,6"
31,Maluku,64.468,"0,2",117,"0,84%",32.951,"231,36","1970,6",32198,"42,1"
32,Papua Barat,32.690,"0,15",97,"1,32%",17.755,"89,41","587,6",131636,"44,4"
33,Papua,75.024,"0,52",343,"1,17%",39.157,"221,27","636,4",59064,"41,5"
34,Papua Tengah,10.736,-,-,"0,99%",8.184,"27,6","1073,6",118774,-
35,Papua Pegunungan,2.410,-,-,"0,90%",998,"4,9","549,7",18105,-
36,Papua Selatan,6.267,-,-,"1,24%",3.118,"14,24","1492,3",61583,-
37,Papua Barat Daya,11.793,-,1,"0,88%",5.691,"24,05","1484,9",59064,-

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Provinsi                                           38 non-null     object
 1   Jumlah Rekening Penerima Pinjaman Aktif (entitas)  38 non-null     object
 2   Jumlah Dana yang Diberikan (Rp miliar)             38 non-null     object
 3    Jumlah Rekening Pemberi Pinjaman (akun)           38 non-null     object
 4   TWP 90%                                            38 non-null     object
 5   Jumlah Penerima Pinjaman (akun)                    38 non-null     object
 6   Outstanding Pinjaman (Rp miliar)                   38 non-null     object
 7   Jumlah Penduduk (Ribu)                             38 non-null     object
 8   PDRB (Ribu Rp)                                     38 non-null     int64
 9   Urbanisasi (%)                                     38 non-null     object
dtypes: int64(1), object(9)
memory usage: 3.1+ KB

In [ ]:
df3.columns = df3.columns.str.strip()

df3 = df3.replace('-', 0)

for col in df3.columns:
    if df3[col].dtype == 'object' and col != 'Provinsi':
        df3[col] = (
            df3[col]
            .astype(str)
            .str.replace(r'[^\d,.-]', '', regex=True)
            .str.replace('.', '', regex=False)
            .str.replace(',', '.', regex=False)
        )
        df3[col] = pd.to_numeric(df3[col], errors='coerce')

# isi NaN dengan 0 biar bisa diubah ke int
df3 = df3.fillna(0)

# ubah otomatis ke int kalau nilainya bulat
import numpy as np
for col in df3.columns:
    if df3[col].dtype == float and np.all(np.isclose(df3[col] % 1, 0)):
        df3[col] = df3[col].astype(int)

display(df3)

,Provinsi,Jumlah Rekening Penerima Pinjaman Aktif (entitas),Jumlah Dana yang Diberikan (Rp miliar),Jumlah Rekening Pemberi Pinjaman (akun),TWP 90%,Jumlah Penerima Pinjaman (akun),Outstanding Pinjaman (Rp miliar),Jumlah Penduduk (Ribu),PDRB (Ribu Rp),Urbanisasi (%)
0,Banten,1742274,601.94,83677,2.73,1244263,6226.21,12537.4,70276,84.9
1,DKI Jakarta,2708907,20964.00,9272715,3.56,2324200,12838.89,10678.0,344350,100.0
2,Jawa Barat,6818787,251.24,143127,3.41,4705372,20751.93,50759.0,56080,89.3
3,Jawa Tengah,2637739,29.46,59501,2.77,1553694,6962.05,38233.9,47972,60.8
4,DI Yogyakarta,394247,7.26,8228,3.31,240062,1207.31,3781.5,51473,84.1
5,Jawa Timur,3048079,132.94,44643,3.29,1895275,10417.68,42089.3,75770,66.7
6,Nangrou Aceh Darusalam,102897,1.63,615,0.82,70593,196.90,5626.0,43782,43.2
7,Sumatera Utara,1036941,26.54,26205,1.55,650944,3078.85,15785.8,73575,68.1
8,Sumatera Barat,400529,1.77,9358,2.40,198642,1398.91,5914.3,57047,63.8
9,Riau,542854,4.45,4273,1.66,282437,1565.78,2213.5,165350,41.8
10,Kepulauan Riau,309076,7.83,9212,1.80,180411,993.02,10678.0,161424,85.3
11,Kepualauan Bangka Belitung,103253,0.91,1080,1.60,54643,337.75,1550.8,70194,67.4
12,Jambi,273264,1.06,1251,2.16,136402,864.30,3768.5,86722,38.2
13,Sumatera Selatan,577990,8.60,4120,2.66,334613,1728.24,8928.5,75132,40.1
14,Bengkulu,138784,0.36,358,1.75,68108,478.30,2138.0,49233,35.6
15,Lampung,530899,5.15,4033,2.81,284856,1455.80,9522.9,51370,42.4
16,Kalimantan Barat,277057,4.73,4654,1.54,151011,855.65,5766.0,52703,47.9
17,Kalimantan Tengah,162309,0.45,506,1.49,90470,488.58,2845.0,79320,52.9
18,Kalimantan Utara,39135,0.15,84,3.08,20761,133.66,749.4,198429,0.0
19,Kalimantan Timur,453429,6.55,1311,1.94,266429,1309.86,4267.6,212175,77.7
20,Kalimantan Selatan,336953,2.29,2214,2.00,190913,958.78,4323.3,67117,59.8
21,Sulawesi Utara,269034,0.78,1493,1.35,152307,976.30,2721.4,69352,68.7
22,Gorontalo,114275,0.35,298,1.40,51903,457.14,1242.2,44433,58.4
23,Sulawesi Tengah,177868,0.64,665,1.54,77106,598.93,3156.1,120750,43.1
24,Sulawesi Barat,57874,0.12,247,1.19,25633,230.51,1525.3,42718,23.1
25,Sulawesi Selatan,609232,6.63,7617,1.67,354031,2038.05,9563.1,73573,59.6
26,Sulawesi Tenggara,140184,0.27,529,1.44,69118,701.29,2836.7,67840,48.3
27,Bali,427124,18.54,8469,1.13,260541,1781.63,2836.7,67319,81.2
28,Nusa Tenggara Barat,237629,1.14,6378,4.36,100966,827.06,5731.1,32282,62.7
29,Nusa Tenggara Timur,226040,0.72,8249,1.41,74766,753.13,5742.6,24272,34.6
30,Maluku Utara,54436,0.08,74,0.62,27649,242.69,1373.8,70660,30.6
31,Maluku,64468,0.20,117,0.84,32951,231.36,1970.6,32198,42.1
32,Papua Barat,32690,0.15,97,1.32,17755,89.41,587.6,131636,44.4
33,Papua,75024,0.52,343,1.17,39157,221.27,636.4,59064,41.5
34,Papua Tengah,10736,0.00,0,0.99,8184,27.60,1073.6,118774,0.0
35,Papua Pegunungan,2410,0.00,0,0.90,998,4.90,549.7,18105,0.0
36,Papua Selatan,6267,0.00,0,1.24,3118,14.24,1492.3,61583,0.0
37,Papua Barat Daya,11793,0.00,1,0.88,5691,24.05,1484.9,59064,0.0

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Provinsi                                           38 non-null     object
 1   Jumlah Rekening Penerima Pinjaman Aktif (entitas)  38 non-null     int64
 2   Jumlah Dana yang Diberikan (Rp miliar)             38 non-null     float64
 3   Jumlah Rekening Pemberi Pinjaman (akun)            38 non-null     int64
 4   TWP 90%                                            38 non-null     float64
 5   Jumlah Penerima Pinjaman (akun)                    38 non-null     int64
 6   Outstanding Pinjaman (Rp miliar)                   38 non-null     float64
 7   Jumlah Penduduk (Ribu)                             38 non-null     float64
 8   PDRB (Ribu Rp)                                     38 non-null     int64
 9   Urbanisasi (%)                                     38 non-null     float64
dtypes: float64(5), int64(4), object(1)
memory usage: 3.1+ KB

In [ ]:
df3.duplicated().sum()

np.int64(0)

In [ ]:
df3.isnull().sum()

Provinsi                                              0
Jumlah Rekening Penerima Pinjaman Aktif (entitas)     0
Jumlah Dana yang Diberikan (Rp miliar)                0
 Jumlah Rekening Pemberi Pinjaman (akun)              0
TWP 90%                                               0
Jumlah Penerima Pinjaman (akun)                       0
Outstanding Pinjaman (Rp miliar)                      0
Jumlah Penduduk (Ribu)                                0
PDRB (Ribu Rp)                                        0
Urbanisasi (%)                                        0
Unnamed: 10                                          38
Unnamed: 11                                          38
Unnamed: 12                                          38
Unnamed: 13                                          38
Unnamed: 14                                          38
Unnamed: 15                                          38
dtype: int64

In [ ]:
# Simpan ke file CSV
df3.to_csv("regional_clean.csv", index=False)

# Unduh file ke komputer (jika di Google Colab)
from google.colab import files
files.download("regional_clean.csv")

In [ ]:
df=pd.read_excel("/content/df_Gen_Z_Financial_Literacy_Survey_clean.xlsx")
df

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,...,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score,Financial_Knowledge_Score.1,Fintech_Literacy_Score.1,Financial_Behavior_Score.1,Financial_Decision_Score.1,Financial_Wellbeing_Score.1
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3.4,2.4,3.1,2.7,2.4,3.4,2.4,3.1,2.7,2.4
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,2.9,3.2,3.0,2.6,2.9,2.9,3.2,3.0,2.6,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3.1,2.6,2.9,2.7,2.2,3.1,2.6,2.9,2.7,2.2
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,2.8,2.4,2.7,2.5,2.4,2.8,2.4,2.7,2.5,2.4
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,...,3.2,3.8,3.9,2.8,2.6,3.2,3.8,3.9,2.8,2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,Male,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2000,Unknown,< Rp2.000.000,...,3.3,2.2,3.3,3.0,1.6,3.3,2.2,3.3,3.0,1.6
1641,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,...,2.2,2.4,2.7,2.8,2.4,2.2,2.4,2.7,2.8,2.4
1642,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Rp2.000.001 – Rp4.000.000,...,1.7,3.1,2.6,2.7,2.1,1.7,3.1,2.6,2.7,2.1
1643,Female,DI Yogyakarta,Unknown,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Unknown,< Rp2.000.000,...,2.8,3.3,2.6,2.9,2.4,2.8,3.3,2.6,2.9,2.4
1644,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,...,2.6,2.7,2.3,2.6,3.0,2.6,2.7,2.3,2.6,3.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1645 entries, 0 to 1644
Data columns (total 21 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Gender                                                         1645 non-null   object
 1   Province of Origin                                             1645 non-null   object
 2   Random_Code                                                    1645 non-null   object
 3   Residence Status                                               1645 non-null   object
 4   Last Education                                                 1645 non-null   object
 5   Job                                                            1645 non-null   object
 6   Marital Status                                                 1645 non-null   object
 7   Year of Birth                                                  1645 non-null   int64
 8   Est. Monthly Income                                            1645 non-null   object
 9   Est. Monthly Expenditure                                       1645 non-null   object
 10  I will achieve the financial goals that I have set for myself  1645 non-null   int64
 11  Financial_Knowledge_Score                                      1645 non-null   float64
 12  Fintech_Literacy_Score                                         1645 non-null   float64
 13  Financial_Behavior_Score                                       1645 non-null   float64
 14  Financial_Decision_Score                                       1645 non-null   float64
 15  Financial_Wellbeing_Score                                      1645 non-null   float64
 16  Financial_Knowledge_Score.1                                    1645 non-null   float64
 17  Fintech_Literacy_Score.1                                       1645 non-null   float64
 18  Financial_Behavior_Score.1                                     1645 non-null   float64
 19  Financial_Decision_Score.1                                     1645 non-null   float64
 20  Financial_Wellbeing_Score.1                                    1645 non-null   float64
dtypes: float64(10), int64(2), object(9)
memory usage: 270.0+ KB

In [ ]:
columns_to_drop = [
    'I will achieve the financial goals that I have set for myself',
    'Financial_Knowledge_Score.1',
    'Fintech_Literacy_Score.1',
    'Financial_Behavior_Score.1',
    'Financial_Decision_Score.1',
    'Financial_Wellbeing_Score.1'
]

df = df.drop(columns=columns_to_drop, errors='ignore')

print("Kolom setelah dihapus:")
print(df.columns)

Kolom setelah dihapus:
Index(['Gender', 'Province of Origin', 'Random_Code', 'Residence Status',
       'Last Education', 'Job', 'Marital Status', 'Year of Birth',
       'Est. Monthly Income', 'Est. Monthly Expenditure',
       'Financial_Knowledge_Score', 'Fintech_Literacy_Score',
       'Financial_Behavior_Score', 'Financial_Decision_Score',
       'Financial_Wellbeing_Score'],
      dtype='object')

In [ ]:
df

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.4,2.4,3.1,2.7,2.4
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.9,3.2,3.0,2.6,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.1,2.6,2.9,2.7,2.2
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.8,2.4,2.7,2.5,2.4
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.2,3.8,3.9,2.8,2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,Male,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2000,Unknown,< Rp2.000.000,3.3,2.2,3.3,3.0,1.6
1641,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,2.2,2.4,2.7,2.8,2.4
1642,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Rp2.000.001 – Rp4.000.000,1.7,3.1,2.6,2.7,2.1
1643,Female,DI Yogyakarta,Unknown,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Unknown,< Rp2.000.000,2.8,3.3,2.6,2.9,2.4
1644,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,2.6,2.7,2.3,2.6,3.0

In [ ]:
# Tentukan kolom yang akan diformat
score_cols = [
    'Financial_Knowledge_Score',
    'Fintech_Literacy_Score',
    'Financial_Behavior_Score',
    'Financial_Decision_Score',
    'Financial_Wellbeing_Score'
]

# Pastikan kolom tersebut diformat dengan satu angka di belakang koma
df[score_cols] = df[score_cols].applymap(lambda x: f"{x:.1f}" if pd.notnull(x) else "")

/tmp/ipython-input-3500527525.py:11: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[score_cols] = df[score_cols].applymap(lambda x: f"{x:.1f}" if pd.notnull(x) else "")

In [ ]:
df

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.4,2.4,3.1,2.7,2.4
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.9,3.2,3.0,2.6,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.1,2.6,2.9,2.7,2.2
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.8,2.4,2.7,2.5,2.4
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.2,3.8,3.9,2.8,2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,Male,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2000,Unknown,< Rp2.000.000,3.3,2.2,3.3,3.0,1.6
1641,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,2.2,2.4,2.7,2.8,2.4
1642,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Rp2.000.001 – Rp4.000.000,1.7,3.1,2.6,2.7,2.1
1643,Female,DI Yogyakarta,Unknown,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Unknown,< Rp2.000.000,2.8,3.3,2.6,2.9,2.4
1644,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,2.6,2.7,2.3,2.6,3.0

In [ ]:
# Simpan ke file Excel
output_path = "/content/Gen_Z_Financial_Literacy_Survey_cleaned_fix.xlsx"
df.to_excel(output_path, index=False)

print(f"✅ Dataset berhasil disimpan ke: {output_path}")

✅ Dataset berhasil disimpan ke: /content/Gen_Z_Financial_Literacy_Survey_cleaned_fix.xlsx

In [ ]:
df=pd.read_excel("/content/drive/MyDrive/GELAR RASA/Dataset/Gen_Z_Financial_Literacy_Survey_cleaned_fix.xlsx")
df

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.4,2.4,3.1,2.7,2.4
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.9,3.2,3.0,2.6,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.1,2.6,2.9,2.7,2.2
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.8,2.4,2.7,2.5,2.4
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.2,3.8,3.9,2.8,2.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,Male,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2000,Unknown,< Rp2.000.000,3.3,2.2,3.3,3.0,1.6
1641,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,2.2,2.4,2.7,2.8,2.4
1642,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Rp2.000.001 – Rp4.000.000,1.7,3.1,2.6,2.7,2.1
1643,Female,DI Yogyakarta,Unknown,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Unknown,< Rp2.000.000,2.8,3.3,2.6,2.9,2.4
1644,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,2.6,2.7,2.3,2.6,3.0

# Kolom Baru Total Skor

In [ ]:
# Daftar kolom yang akan dijumlahkan
score_cols = [
    'Financial_Knowledge_Score',
    'Fintech_Literacy_Score',
    'Financial_Behavior_Score',
    'Financial_Decision_Score',
    'Financial_Wellbeing_Score'
]

# Pastikan kolom dalam bentuk numerik (jaga-jaga jika sebelumnya disimpan sebagai string)
df[score_cols] = df[score_cols].apply(pd.to_numeric, errors='coerce')

# Buat kolom baru Total_Score
df['Total_Score'] = df[score_cols].mean(axis=1).round(1)

# Bulatkan ke 1 angka di belakang koma biar konsisten
df['Total_Score'] = df['Total_Score'].round(1)

# Cek hasilnya
print(df[['Financial_Knowledge_Score', 'Fintech_Literacy_Score',
                'Financial_Behavior_Score', 'Financial_Decision_Score',
                'Financial_Wellbeing_Score', 'Total_Score']].head())

   Financial_Knowledge_Score  Fintech_Literacy_Score  \
0                        3.4                     2.4
1                        2.9                     3.2
2                        3.1                     2.6
3                        2.8                     2.4
4                        3.2                     3.8

   Financial_Behavior_Score  Financial_Decision_Score  \
0                       3.1                       2.7
1                       3.0                       2.6
2                       2.9                       2.7
3                       2.7                       2.5
4                       3.9                       2.8

   Financial_Wellbeing_Score  Total_Score
0                        2.4          2.8
1                        2.9          2.9
2                        2.2          2.7
3                        2.4          2.6
4                        2.6          3.3

In [ ]:
df

,Gender,Province of Origin,Random_Code,Residence Status,Last Education,Job,Marital Status,Year of Birth,Est. Monthly Income,Est. Monthly Expenditure,Financial_Knowledge_Score,Fintech_Literacy_Score,Financial_Behavior_Score,Financial_Decision_Score,Financial_Wellbeing_Score,Total_Score
0,Female,West Sumatera,B99Z,Family House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.4,2.4,3.1,2.7,2.4,2.8
1,Female,West Sumatera,A96P,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.9,3.2,3.0,2.6,2.9,2.9
2,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Civil Servant/BUMN,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.1,2.6,2.9,2.7,2.2,2.7
3,Female,West Sumatera,C77Q,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,2.8,2.4,2.7,2.5,2.4,2.6
4,Female,West Sumatera,B99Z,Parent’s House,Diploma I/II/III,Student,Not Married,2000,< Rp2.000.000,< Rp2.000.000,3.2,3.8,3.9,2.8,2.6,3.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,Male,West Sumatera,Unknown,Parent’s House,Senior High School (SMA),Student,Not Married,2000,Unknown,< Rp2.000.000,3.3,2.2,3.3,3.0,1.6,2.7
1641,Male,East Java,A12X,Rental House,Senior High School (SMA),Student,Not Married,2003,< Rp2.000.000,< Rp2.000.000,2.2,2.4,2.7,2.8,2.4,2.5
1642,Male,West Sumatera,B99Z,Parent’s House,Senior High School (SMA),Student,Not Married,2004,Rp4.000.001 - Rp6.000.000,Rp2.000.001 – Rp4.000.000,1.7,3.1,2.6,2.7,2.1,2.4
1643,Female,DI Yogyakarta,Unknown,Parent’s House,Bachelor (S1)/Diploma IV,Student,Not Married,2003,Unknown,< Rp2.000.000,2.8,3.3,2.6,2.9,2.4,2.8
1644,Female,West Sumatera,B99Z,Rental House,Senior High School (SMA),Student,Not Married,2004,< Rp2.000.000,< Rp2.000.000,2.6,2.7,2.3,2.6,3.0,2.6